/* Generated by Yosys 0.7 (git sha1 UNKNOWN, gcc 4.9.2-10 -fPIC -Os) */

`include "cmos_cells.v"

(* src = "Reset_Module.v:24" *)
module Reset_Module(CLK, reset, ioTRANSMIT, iAlert, oTRANSMIT, ALERT, oRECEIVE_DETECT, oRECEIVE_BYTE_COUNT, PHY_Stop_Attempting_Reset);
  (* src = "Reset_Module.v:84" *)
  wire [15:0] _000_;
  (* src = "Reset_Module.v:84" *)
  wire [7:0] _001_;
  (* src = "Reset_Module.v:84" *)
  wire [7:0] _002_;
  (* src = "Reset_Module.v:84" *)
  wire [7:0] _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire [5:0] _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire [4:0] _219_;
  wire [1:0] _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire [2:0] _224_;
  wire [2:0] _225_;
  wire [2:0] _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  (* src = "Reset_Module.v:133" *)
  wire _230_;
  (* src = "Reset_Module.v:164" *)
  wire _231_;
  (* src = "Reset_Module.v:130" *)
  wire _232_;
  wire [7:0] _233_;
  wire [7:0] _234_;
  wire [7:0] _235_;
  wire [7:0] _236_;
  wire [7:0] _237_;
  wire [7:0] _238_;
  wire [7:0] _239_;
  (* src = "<techmap.v>:260|<techmap.v>:203" *)
  wire [31:0] _240_;
  (* src = "<techmap.v>:260|<techmap.v>:203" *)
  wire [31:0] _241_;
  wire [31:0] _242_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _243_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _244_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _245_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _246_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _247_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _248_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _249_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _250_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _251_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _252_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _253_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _254_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _255_;
  (* src = "Reset_Module.v:42" *)
  output [15:0] ALERT;
  (* src = "Reset_Module.v:36" *)
  input CLK;
  (* src = "Reset_Module.v:43" *)
  output PHY_Stop_Attempting_Reset;
  (* src = "Reset_Module.v:58" *)
  wire PHY_reset;
  (* src = "Reset_Module.v:37" *)
  input [15:0] iAlert;
  (* src = "Reset_Module.v:38" *)
  input [7:0] ioTRANSMIT;
  (* src = "Reset_Module.v:49" *)
  wire [9:0] nanos;
  (* src = "Reset_Module.v:50" *)
  wire [15:0] nxt_ALERT;
  (* src = "Reset_Module.v:52" *)
  wire [7:0] nxt_oRECEIVE_BYTE_COUNT;
  (* src = "Reset_Module.v:53" *)
  wire [7:0] nxt_oRECEIVE_DETECT;
  (* src = "Reset_Module.v:56" *)
  wire [7:0] nxt_oTRANSMIT;
  (* src = "Reset_Module.v:44" *)
  output [7:0] oRECEIVE_BYTE_COUNT;
  (* src = "Reset_Module.v:45" *)
  output [7:0] oRECEIVE_DETECT;
  (* src = "Reset_Module.v:46" *)
  output [7:0] oTRANSMIT;
  (* src = "Reset_Module.v:39" *)
  input reset;
  (* onehot = 32'd1 *)
  wire [5:0] state;
  NOR _256_ (
    .A(_179_),
    .B(_176_),
    .Y(_004_)
  );
  NOT _257_ (
    .A(_174_),
    .Y(_005_)
  );
  NOT _258_ (
    .A(_175_),
    .Y(_006_)
  );
  NAND _259_ (
    .A(_006_),
    .B(_005_),
    .Y(_007_)
  );
  NOR _260_ (
    .A(_007_),
    .B(_177_),
    .Y(_008_)
  );
  NAND _261_ (
    .A(_008_),
    .B(_004_),
    .Y(_009_)
  );
  NOT _262_ (
    .A(_182_),
    .Y(_010_)
  );
  NAND _263_ (
    .A(_181_),
    .B(_180_),
    .Y(_011_)
  );
  NOR _264_ (
    .A(_011_),
    .B(_010_),
    .Y(_013_)
  );
  NAND _265_ (
    .A(_013_),
    .B(_009_),
    .Y(_014_)
  );
  NAND _266_ (
    .A(_014_),
    .B(_192_),
    .Y(_016_)
  );
  NOR _267_ (
    .A(_016_),
    .B(_183_),
    .Y(_017_)
  );
  NOR _268_ (
    .A(_017_),
    .B(_155_),
    .Y(_019_)
  );
  NOR _269_ (
    .A(_019_),
    .B(_178_),
    .Y(_034_)
  );
  NAND _270_ (
    .A(_149_),
    .B(_147_),
    .Y(_021_)
  );
  NOR _271_ (
    .A(_021_),
    .B(_144_),
    .Y(_022_)
  );
  NOT _272_ (
    .A(_192_),
    .Y(_024_)
  );
  NOT _273_ (
    .A(_179_),
    .Y(_025_)
  );
  NOR _274_ (
    .A(_177_),
    .B(_176_),
    .Y(_027_)
  );
  NAND _275_ (
    .A(_027_),
    .B(_025_),
    .Y(_028_)
  );
  NOR _276_ (
    .A(_028_),
    .B(_007_),
    .Y(_030_)
  );
  NOT _277_ (
    .A(_180_),
    .Y(_031_)
  );
  NOT _278_ (
    .A(_181_),
    .Y(_033_)
  );
  NOR _279_ (
    .A(_033_),
    .B(_031_),
    .Y(_035_)
  );
  NAND _280_ (
    .A(_035_),
    .B(_182_),
    .Y(_037_)
  );
  NOR _281_ (
    .A(_037_),
    .B(_030_),
    .Y(_038_)
  );
  NOR _282_ (
    .A(_038_),
    .B(_024_),
    .Y(_040_)
  );
  NAND _283_ (
    .A(_040_),
    .B(_183_),
    .Y(_041_)
  );
  NOR _284_ (
    .A(_041_),
    .B(_022_),
    .Y(_043_)
  );
  NOR _285_ (
    .A(_043_),
    .B(_057_),
    .Y(_044_)
  );
  NOR _286_ (
    .A(_044_),
    .B(_178_),
    .Y(_069_)
  );
  NOT _287_ (
    .A(_178_),
    .Y(_046_)
  );
  NAND _288_ (
    .A(_061_),
    .B(_046_),
    .Y(_048_)
  );
  NOR _289_ (
    .A(_041_),
    .B(_178_),
    .Y(_152_)
  );
  NAND _290_ (
    .A(_152_),
    .B(_022_),
    .Y(_051_)
  );
  NAND _291_ (
    .A(_051_),
    .B(_048_),
    .Y(_070_)
  );
  NOT _292_ (
    .A(_183_),
    .Y(_053_)
  );
  NOR _293_ (
    .A(_016_),
    .B(_053_),
    .Y(_054_)
  );
  NOR _294_ (
    .A(_054_),
    .B(_064_),
    .Y(_056_)
  );
  NOR _295_ (
    .A(_056_),
    .B(_178_),
    .Y(_072_)
  );
  NOT _296_ (
    .A(_073_),
    .Y(_058_)
  );
  NOR _297_ (
    .A(_058_),
    .B(_178_),
    .Y(_075_)
  );
  NOT _298_ (
    .A(_076_),
    .Y(_059_)
  );
  NOR _299_ (
    .A(_059_),
    .B(_178_),
    .Y(_078_)
  );
  NOT _300_ (
    .A(_079_),
    .Y(_062_)
  );
  NOR _301_ (
    .A(_062_),
    .B(_178_),
    .Y(_082_)
  );
  NOT _302_ (
    .A(_083_),
    .Y(_063_)
  );
  NOR _303_ (
    .A(_063_),
    .B(_178_),
    .Y(_085_)
  );
  NOT _304_ (
    .A(_086_),
    .Y(_065_)
  );
  NOR _305_ (
    .A(_065_),
    .B(_178_),
    .Y(_088_)
  );
  NAND _306_ (
    .A(_193_),
    .B(_046_),
    .Y(_066_)
  );
  NOR _307_ (
    .A(_066_),
    .B(_054_),
    .Y(_090_)
  );
  NAND _308_ (
    .A(_194_),
    .B(_046_),
    .Y(_067_)
  );
  NOR _309_ (
    .A(_067_),
    .B(_054_),
    .Y(_092_)
  );
  NAND _310_ (
    .A(_195_),
    .B(_046_),
    .Y(_068_)
  );
  NOR _311_ (
    .A(_068_),
    .B(_054_),
    .Y(_093_)
  );
  NAND _312_ (
    .A(_196_),
    .B(_046_),
    .Y(_071_)
  );
  NOR _313_ (
    .A(_071_),
    .B(_054_),
    .Y(_095_)
  );
  NAND _314_ (
    .A(_197_),
    .B(_046_),
    .Y(_074_)
  );
  NOR _315_ (
    .A(_074_),
    .B(_054_),
    .Y(_096_)
  );
  NAND _316_ (
    .A(_198_),
    .B(_046_),
    .Y(_077_)
  );
  NOR _317_ (
    .A(_077_),
    .B(_054_),
    .Y(_099_)
  );
  NAND _318_ (
    .A(_199_),
    .B(_046_),
    .Y(_080_)
  );
  NOR _319_ (
    .A(_080_),
    .B(_054_),
    .Y(_100_)
  );
  NAND _320_ (
    .A(_200_),
    .B(_046_),
    .Y(_084_)
  );
  NOR _321_ (
    .A(_084_),
    .B(_054_),
    .Y(_102_)
  );
  NOT _322_ (
    .A(_184_),
    .Y(_087_)
  );
  NAND _323_ (
    .A(_041_),
    .B(_087_),
    .Y(_089_)
  );
  NAND _324_ (
    .A(_089_),
    .B(_046_),
    .Y(_091_)
  );
  NOR _325_ (
    .A(_091_),
    .B(_043_),
    .Y(_103_)
  );
  NAND _326_ (
    .A(_185_),
    .B(_046_),
    .Y(_094_)
  );
  NOR _327_ (
    .A(_094_),
    .B(_054_),
    .Y(_105_)
  );
  NAND _328_ (
    .A(_186_),
    .B(_046_),
    .Y(_097_)
  );
  NOR _329_ (
    .A(_097_),
    .B(_054_),
    .Y(_106_)
  );
  NAND _330_ (
    .A(_187_),
    .B(_046_),
    .Y(_101_)
  );
  NOR _331_ (
    .A(_101_),
    .B(_054_),
    .Y(_108_)
  );
  NAND _332_ (
    .A(_188_),
    .B(_046_),
    .Y(_104_)
  );
  NOR _333_ (
    .A(_104_),
    .B(_054_),
    .Y(_109_)
  );
  NAND _334_ (
    .A(_189_),
    .B(_046_),
    .Y(_107_)
  );
  NOR _335_ (
    .A(_107_),
    .B(_054_),
    .Y(_111_)
  );
  NAND _336_ (
    .A(_190_),
    .B(_046_),
    .Y(_110_)
  );
  NOR _337_ (
    .A(_110_),
    .B(_054_),
    .Y(_112_)
  );
  NAND _338_ (
    .A(_191_),
    .B(_046_),
    .Y(_113_)
  );
  NOR _339_ (
    .A(_113_),
    .B(_054_),
    .Y(_114_)
  );
  NOT _340_ (
    .A(_012_),
    .Y(_116_)
  );
  NOT _341_ (
    .A(_081_),
    .Y(_118_)
  );
  NAND _342_ (
    .A(_118_),
    .B(_046_),
    .Y(_120_)
  );
  NOR _343_ (
    .A(_120_),
    .B(_116_),
    .Y(_115_)
  );
  NOT _344_ (
    .A(_015_),
    .Y(_123_)
  );
  NOR _345_ (
    .A(_120_),
    .B(_123_),
    .Y(_117_)
  );
  NOT _346_ (
    .A(_018_),
    .Y(_126_)
  );
  NOR _347_ (
    .A(_120_),
    .B(_126_),
    .Y(_119_)
  );
  NOT _348_ (
    .A(_020_),
    .Y(_129_)
  );
  NOR _349_ (
    .A(_120_),
    .B(_129_),
    .Y(_121_)
  );
  NOR _350_ (
    .A(_160_),
    .B(_118_),
    .Y(_132_)
  );
  NOT _351_ (
    .A(_166_),
    .Y(_134_)
  );
  NAND _352_ (
    .A(_031_),
    .B(_134_),
    .Y(_136_)
  );
  NAND _353_ (
    .A(_010_),
    .B(_033_),
    .Y(_138_)
  );
  NOR _354_ (
    .A(_138_),
    .B(_136_),
    .Y(_140_)
  );
  NAND _355_ (
    .A(_140_),
    .B(_132_),
    .Y(_142_)
  );
  NOR _356_ (
    .A(_142_),
    .B(_009_),
    .Y(_143_)
  );
  NOT _357_ (
    .A(_023_),
    .Y(_145_)
  );
  NAND _358_ (
    .A(_145_),
    .B(_118_),
    .Y(_146_)
  );
  NAND _359_ (
    .A(_146_),
    .B(_046_),
    .Y(_148_)
  );
  NOR _360_ (
    .A(_148_),
    .B(_143_),
    .Y(_122_)
  );
  NOT _361_ (
    .A(_026_),
    .Y(_151_)
  );
  NOR _362_ (
    .A(_120_),
    .B(_151_),
    .Y(_124_)
  );
  NOT _363_ (
    .A(_029_),
    .Y(_154_)
  );
  NOR _364_ (
    .A(_154_),
    .B(_081_),
    .Y(_156_)
  );
  NOR _365_ (
    .A(_156_),
    .B(_143_),
    .Y(_158_)
  );
  NOR _366_ (
    .A(_158_),
    .B(_178_),
    .Y(_125_)
  );
  NOT _367_ (
    .A(_032_),
    .Y(_159_)
  );
  NOR _368_ (
    .A(_120_),
    .B(_159_),
    .Y(_127_)
  );
  NOT _369_ (
    .A(_036_),
    .Y(_161_)
  );
  NOR _370_ (
    .A(_120_),
    .B(_161_),
    .Y(_128_)
  );
  NOT _371_ (
    .A(_039_),
    .Y(_162_)
  );
  NOR _372_ (
    .A(_120_),
    .B(_162_),
    .Y(_130_)
  );
  NOT _373_ (
    .A(_042_),
    .Y(_163_)
  );
  NOR _374_ (
    .A(_120_),
    .B(_163_),
    .Y(_131_)
  );
  NOT _375_ (
    .A(_045_),
    .Y(_164_)
  );
  NOR _376_ (
    .A(_120_),
    .B(_164_),
    .Y(_133_)
  );
  NOT _377_ (
    .A(_047_),
    .Y(_165_)
  );
  NOR _378_ (
    .A(_120_),
    .B(_165_),
    .Y(_135_)
  );
  NOT _379_ (
    .A(_050_),
    .Y(_167_)
  );
  NOR _380_ (
    .A(_120_),
    .B(_167_),
    .Y(_137_)
  );
  NOT _381_ (
    .A(_052_),
    .Y(_168_)
  );
  NOR _382_ (
    .A(_120_),
    .B(_168_),
    .Y(_139_)
  );
  NOT _383_ (
    .A(_055_),
    .Y(_169_)
  );
  NOR _384_ (
    .A(_120_),
    .B(_169_),
    .Y(_141_)
  );
  NOR _385_ (
    .A(_060_),
    .B(_049_),
    .Y(_170_)
  );
  NOR _386_ (
    .A(_170_),
    .B(_178_),
    .Y(_150_)
  );
  NAND _387_ (
    .A(_192_),
    .B(_046_),
    .Y(_171_)
  );
  NOR _388_ (
    .A(_171_),
    .B(_014_),
    .Y(_153_)
  );
  NOR _389_ (
    .A(_098_),
    .B(_081_),
    .Y(_172_)
  );
  NAND _390_ (
    .A(_170_),
    .B(_046_),
    .Y(_173_)
  );
  NOR _391_ (
    .A(_173_),
    .B(_172_),
    .Y(_157_)
  );
  DFF _392_ (
    .C(CLK),
    .D(reset),
    .Q(state[0])
  );
  DFF _393_ (
    .C(CLK),
    .D(_203_),
    .Q(state[1])
  );
  DFF _394_ (
    .C(CLK),
    .D(_204_),
    .Q(state[2])
  );
  DFF _395_ (
    .C(CLK),
    .D(_205_),
    .Q(state[3])
  );
  DFF _396_ (
    .C(CLK),
    .D(_209_[4]),
    .Q(state[4])
  );
  DFF _397_ (
    .C(CLK),
    .D(_208_),
    .Q(state[5])
  );
  DFF _398_ (
    .C(CLK),
    .D(_000_[0]),
    .Q(ALERT[0])
  );
  DFF _399_ (
    .C(CLK),
    .D(_000_[1]),
    .Q(ALERT[1])
  );
  DFF _400_ (
    .C(CLK),
    .D(_000_[2]),
    .Q(ALERT[2])
  );
  DFF _401_ (
    .C(CLK),
    .D(_000_[3]),
    .Q(ALERT[3])
  );
  DFF _402_ (
    .C(CLK),
    .D(_000_[4]),
    .Q(ALERT[4])
  );
  DFF _403_ (
    .C(CLK),
    .D(_000_[5]),
    .Q(ALERT[5])
  );
  DFF _404_ (
    .C(CLK),
    .D(_000_[6]),
    .Q(ALERT[6])
  );
  DFF _405_ (
    .C(CLK),
    .D(_000_[7]),
    .Q(ALERT[7])
  );
  DFF _406_ (
    .C(CLK),
    .D(_000_[8]),
    .Q(ALERT[8])
  );
  DFF _407_ (
    .C(CLK),
    .D(_000_[9]),
    .Q(ALERT[9])
  );
  DFF _408_ (
    .C(CLK),
    .D(_000_[10]),
    .Q(ALERT[10])
  );
  DFF _409_ (
    .C(CLK),
    .D(_000_[11]),
    .Q(ALERT[11])
  );
  DFF _410_ (
    .C(CLK),
    .D(_000_[12]),
    .Q(ALERT[12])
  );
  DFF _411_ (
    .C(CLK),
    .D(_000_[13]),
    .Q(ALERT[13])
  );
  DFF _412_ (
    .C(CLK),
    .D(_000_[14]),
    .Q(ALERT[14])
  );
  DFF _413_ (
    .C(CLK),
    .D(_000_[15]),
    .Q(ALERT[15])
  );
  DFF _414_ (
    .C(CLK),
    .D(_001_[0]),
    .Q(oRECEIVE_BYTE_COUNT[0])
  );
  DFF _415_ (
    .C(CLK),
    .D(_001_[1]),
    .Q(oRECEIVE_BYTE_COUNT[1])
  );
  DFF _416_ (
    .C(CLK),
    .D(_001_[2]),
    .Q(oRECEIVE_BYTE_COUNT[2])
  );
  DFF _417_ (
    .C(CLK),
    .D(_001_[3]),
    .Q(oRECEIVE_BYTE_COUNT[3])
  );
  DFF _418_ (
    .C(CLK),
    .D(_001_[4]),
    .Q(oRECEIVE_BYTE_COUNT[4])
  );
  DFF _419_ (
    .C(CLK),
    .D(_001_[5]),
    .Q(oRECEIVE_BYTE_COUNT[5])
  );
  DFF _420_ (
    .C(CLK),
    .D(_001_[6]),
    .Q(oRECEIVE_BYTE_COUNT[6])
  );
  DFF _421_ (
    .C(CLK),
    .D(_001_[7]),
    .Q(oRECEIVE_BYTE_COUNT[7])
  );
  DFF _422_ (
    .C(CLK),
    .D(_002_[0]),
    .Q(oRECEIVE_DETECT[0])
  );
  DFF _423_ (
    .C(CLK),
    .D(_002_[1]),
    .Q(oRECEIVE_DETECT[1])
  );
  DFF _424_ (
    .C(CLK),
    .D(_002_[2]),
    .Q(oRECEIVE_DETECT[2])
  );
  DFF _425_ (
    .C(CLK),
    .D(_002_[3]),
    .Q(oRECEIVE_DETECT[3])
  );
  DFF _426_ (
    .C(CLK),
    .D(_002_[4]),
    .Q(oRECEIVE_DETECT[4])
  );
  DFF _427_ (
    .C(CLK),
    .D(_002_[5]),
    .Q(oRECEIVE_DETECT[5])
  );
  DFF _428_ (
    .C(CLK),
    .D(_002_[6]),
    .Q(oRECEIVE_DETECT[6])
  );
  DFF _429_ (
    .C(CLK),
    .D(_002_[7]),
    .Q(oRECEIVE_DETECT[7])
  );
  DFF _430_ (
    .C(CLK),
    .D(_003_[0]),
    .Q(oTRANSMIT[0])
  );
  DFF _431_ (
    .C(CLK),
    .D(_003_[1]),
    .Q(oTRANSMIT[1])
  );
  DFF _432_ (
    .C(CLK),
    .D(_003_[2]),
    .Q(oTRANSMIT[2])
  );
  DFF _433_ (
    .C(CLK),
    .D(_003_[3]),
    .Q(oTRANSMIT[3])
  );
  DFF _434_ (
    .C(CLK),
    .D(_003_[4]),
    .Q(oTRANSMIT[4])
  );
  DFF _435_ (
    .C(CLK),
    .D(_003_[5]),
    .Q(oTRANSMIT[5])
  );
  DFF _436_ (
    .C(CLK),
    .D(_003_[6]),
    .Q(oTRANSMIT[6])
  );
  DFF _437_ (
    .C(CLK),
    .D(_003_[7]),
    .Q(oTRANSMIT[7])
  );
  (* src = "Reset_Module.v:67" *)
  timer t1 (
    .CLK(CLK),
    .micros(),
    .milis(),
    .nanos(nanos),
    .reset(1'b1),
    .segs()
  );
  assign PHY_Stop_Attempting_Reset = 1'b0;
  assign PHY_reset = iAlert[3];
  assign nxt_oTRANSMIT[7:3] = oTRANSMIT[7:3];
  assign _178_ = reset;
  assign _183_ = iAlert[3];
  assign _209_[4] = _034_;
  assign _049_ = state[3];
  assign _060_ = state[2];
  assign _081_ = state[1];
  assign _098_ = state[0];
  assign _160_ = nanos[0];
  assign _166_ = nanos[1];
  assign _174_ = nanos[2];
  assign _175_ = nanos[3];
  assign _176_ = nanos[4];
  assign _177_ = nanos[5];
  assign _179_ = nanos[6];
  assign _180_ = nanos[7];
  assign _181_ = nanos[8];
  assign _182_ = nanos[9];
  assign _184_ = oRECEIVE_BYTE_COUNT[0];
  assign _185_ = oRECEIVE_BYTE_COUNT[1];
  assign _186_ = oRECEIVE_BYTE_COUNT[2];
  assign _187_ = oRECEIVE_BYTE_COUNT[3];
  assign _188_ = oRECEIVE_BYTE_COUNT[4];
  assign _189_ = oRECEIVE_BYTE_COUNT[5];
  assign _190_ = oRECEIVE_BYTE_COUNT[6];
  assign _191_ = oRECEIVE_BYTE_COUNT[7];
  assign _192_ = state[4];
  assign _193_ = oRECEIVE_DETECT[0];
  assign _194_ = oRECEIVE_DETECT[1];
  assign _195_ = oRECEIVE_DETECT[2];
  assign _196_ = oRECEIVE_DETECT[3];
  assign _197_ = oRECEIVE_DETECT[4];
  assign _198_ = oRECEIVE_DETECT[5];
  assign _199_ = oRECEIVE_DETECT[6];
  assign _200_ = oRECEIVE_DETECT[7];
  assign _012_ = ALERT[0];
  assign _015_ = ALERT[1];
  assign _018_ = ALERT[2];
  assign _020_ = ALERT[3];
  assign _023_ = ALERT[4];
  assign _026_ = ALERT[5];
  assign _029_ = ALERT[6];
  assign _032_ = ALERT[7];
  assign _036_ = ALERT[8];
  assign _039_ = ALERT[9];
  assign _042_ = ALERT[10];
  assign _045_ = ALERT[11];
  assign _047_ = ALERT[12];
  assign _050_ = ALERT[13];
  assign _052_ = ALERT[14];
  assign _055_ = ALERT[15];
  assign _057_ = oTRANSMIT[0];
  assign _061_ = oTRANSMIT[1];
  assign _064_ = oTRANSMIT[2];
  assign _003_[0] = _069_;
  assign _003_[1] = _070_;
  assign _003_[2] = _072_;
  assign _073_ = oTRANSMIT[3];
  assign _003_[3] = _075_;
  assign _076_ = oTRANSMIT[4];
  assign _003_[4] = _078_;
  assign _079_ = oTRANSMIT[5];
  assign _003_[5] = _082_;
  assign _083_ = oTRANSMIT[6];
  assign _003_[6] = _085_;
  assign _086_ = oTRANSMIT[7];
  assign _003_[7] = _088_;
  assign _002_[0] = _090_;
  assign _002_[1] = _092_;
  assign _002_[2] = _093_;
  assign _002_[3] = _095_;
  assign _002_[4] = _096_;
  assign _002_[5] = _099_;
  assign _002_[6] = _100_;
  assign _002_[7] = _102_;
  assign _001_[0] = _103_;
  assign _001_[1] = _105_;
  assign _001_[2] = _106_;
  assign _001_[3] = _108_;
  assign _001_[4] = _109_;
  assign _001_[5] = _111_;
  assign _001_[6] = _112_;
  assign _001_[7] = _114_;
  assign _000_[0] = _115_;
  assign _000_[1] = _117_;
  assign _000_[2] = _119_;
  assign _000_[3] = _121_;
  assign _000_[4] = _122_;
  assign _000_[5] = _124_;
  assign _000_[6] = _125_;
  assign _000_[7] = _127_;
  assign _000_[8] = _128_;
  assign _000_[9] = _130_;
  assign _000_[10] = _131_;
  assign _000_[11] = _133_;
  assign _000_[12] = _135_;
  assign _000_[13] = _137_;
  assign _000_[14] = _139_;
  assign _000_[15] = _141_;
  assign _144_ = ioTRANSMIT[0];
  assign _147_ = ioTRANSMIT[1];
  assign _149_ = ioTRANSMIT[2];
  assign _203_ = _150_;
  assign _205_ = _152_;
  assign _204_ = _153_;
  assign _155_ = state[5];
  assign _208_ = _157_;
endmodule

(* src = "timer.v:25" *)
module timer(CLK, nanos, micros, milis, segs, reset);
  (* src = "timer.v:37" *)
  wire [9:0] _000_;
  (* src = "timer.v:37" *)
  wire [9:0] _001_;
  (* src = "timer.v:37" *)
  wire [9:0] _002_;
  (* src = "timer.v:37" *)
  wire [9:0] _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  (* src = "timer.v:45" *)
  wire [31:0] _330_;
  (* src = "timer.v:49" *)
  wire [31:0] _331_;
  (* src = "timer.v:56" *)
  wire [31:0] _332_;
  (* src = "timer.v:51" *)
  wire _333_;
  wire [9:0] _334_;
  wire [9:0] _335_;
  wire [9:0] _336_;
  wire [9:0] _337_;
  wire [9:0] _338_;
  wire [9:0] _339_;
  wire [9:0] _340_;
  wire [9:0] _341_;
  wire [9:0] _342_;
  wire [9:0] _343_;
  (* src = "<techmap.v>:260|<techmap.v>:203" *)
  wire [31:0] _344_;
  (* src = "<techmap.v>:260|<techmap.v>:203" *)
  wire [31:0] _345_;
  (* src = "<techmap.v>:260|<techmap.v>:203" *)
  wire [31:0] _346_;
  (* src = "<techmap.v>:260|<techmap.v>:203" *)
  wire [31:0] _347_;
  wire [31:0] _348_;
  (* src = "<techmap.v>:260|<techmap.v>:203" *)
  wire [31:0] _349_;
  wire [31:0] _350_;
  (* src = "<techmap.v>:260|<techmap.v>:203" *)
  wire [31:0] _351_;
  wire [31:0] _352_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _353_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _354_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _355_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _356_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _357_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _358_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _359_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _360_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _361_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _362_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _363_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _364_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _365_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _366_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _367_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _368_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _369_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _370_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _371_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _372_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _373_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _374_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _375_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _376_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _377_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _378_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _379_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _380_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _381_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _382_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _383_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _384_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _385_;
  (* src = "timer.v:34" *)
  input CLK;
  (* src = "timer.v:29" *)
  output [9:0] micros;
  (* src = "timer.v:30" *)
  output [9:0] milis;
  (* src = "timer.v:28" *)
  output [9:0] nanos;
  (* src = "timer.v:35" *)
  input reset;
  (* src = "timer.v:31" *)
  output [9:0] segs;
  NOT _386_ (
    .A(_285_),
    .Y(_306_)
  );
  NOT _387_ (
    .A(_211_),
    .Y(_308_)
  );
  NOT _388_ (
    .A(_104_),
    .Y(_309_)
  );
  NOT _389_ (
    .A(_096_),
    .Y(_310_)
  );
  NOT _390_ (
    .A(_099_),
    .Y(_311_)
  );
  NOR _391_ (
    .A(_311_),
    .B(_310_),
    .Y(_312_)
  );
  NAND _392_ (
    .A(_312_),
    .B(_102_),
    .Y(_313_)
  );
  NAND _393_ (
    .A(_313_),
    .B(_309_),
    .Y(_314_)
  );
  NOR _394_ (
    .A(_314_),
    .B(_107_),
    .Y(_315_)
  );
  NOT _395_ (
    .A(_110_),
    .Y(_316_)
  );
  NAND _396_ (
    .A(_115_),
    .B(_112_),
    .Y(_317_)
  );
  NOR _397_ (
    .A(_317_),
    .B(_316_),
    .Y(_318_)
  );
  NAND _398_ (
    .A(_120_),
    .B(_117_),
    .Y(_319_)
  );
  NOT _399_ (
    .A(_319_),
    .Y(_321_)
  );
  NAND _400_ (
    .A(_321_),
    .B(_318_),
    .Y(_323_)
  );
  NOR _401_ (
    .A(_323_),
    .B(_315_),
    .Y(_325_)
  );
  NOT _402_ (
    .A(_296_),
    .Y(_327_)
  );
  NOT _403_ (
    .A(_297_),
    .Y(_329_)
  );
  NOR _404_ (
    .A(_329_),
    .B(_327_),
    .Y(_007_)
  );
  NAND _405_ (
    .A(_007_),
    .B(_298_),
    .Y(_009_)
  );
  NOR _406_ (
    .A(_301_),
    .B(_300_),
    .Y(_011_)
  );
  NAND _407_ (
    .A(_011_),
    .B(_009_),
    .Y(_013_)
  );
  NAND _408_ (
    .A(_307_),
    .B(_304_),
    .Y(_015_)
  );
  NOT _409_ (
    .A(_302_),
    .Y(_017_)
  );
  NOT _410_ (
    .A(_303_),
    .Y(_018_)
  );
  NOR _411_ (
    .A(_018_),
    .B(_017_),
    .Y(_020_)
  );
  NAND _412_ (
    .A(_020_),
    .B(_305_),
    .Y(_021_)
  );
  NOR _413_ (
    .A(_021_),
    .B(_015_),
    .Y(_023_)
  );
  NAND _414_ (
    .A(_023_),
    .B(_013_),
    .Y(_024_)
  );
  NOT _415_ (
    .A(_016_),
    .Y(_026_)
  );
  NOT _416_ (
    .A(_019_),
    .Y(_027_)
  );
  NOR _417_ (
    .A(_027_),
    .B(_026_),
    .Y(_029_)
  );
  NAND _418_ (
    .A(_029_),
    .B(_022_),
    .Y(_030_)
  );
  NOR _419_ (
    .A(_028_),
    .B(_025_),
    .Y(_032_)
  );
  NAND _420_ (
    .A(_032_),
    .B(_030_),
    .Y(_033_)
  );
  NAND _421_ (
    .A(_034_),
    .B(_031_),
    .Y(_035_)
  );
  NOT _422_ (
    .A(_037_),
    .Y(_036_)
  );
  NOT _423_ (
    .A(_040_),
    .Y(_038_)
  );
  NOR _424_ (
    .A(_038_),
    .B(_036_),
    .Y(_039_)
  );
  NAND _425_ (
    .A(_039_),
    .B(_043_),
    .Y(_041_)
  );
  NOR _426_ (
    .A(_041_),
    .B(_035_),
    .Y(_042_)
  );
  NAND _427_ (
    .A(_042_),
    .B(_033_),
    .Y(_044_)
  );
  NOR _428_ (
    .A(_044_),
    .B(_024_),
    .Y(_045_)
  );
  NAND _429_ (
    .A(_045_),
    .B(_325_),
    .Y(_046_)
  );
  NAND _430_ (
    .A(_046_),
    .B(_308_),
    .Y(_047_)
  );
  NAND _431_ (
    .A(_047_),
    .B(_306_),
    .Y(_048_)
  );
  NOR _432_ (
    .A(_046_),
    .B(_308_),
    .Y(_049_)
  );
  NOR _433_ (
    .A(_049_),
    .B(_048_),
    .Y(_286_)
  );
  NOT _434_ (
    .A(_004_),
    .Y(_051_)
  );
  NOT _435_ (
    .A(_107_),
    .Y(_052_)
  );
  NOT _436_ (
    .A(_102_),
    .Y(_053_)
  );
  NAND _437_ (
    .A(_099_),
    .B(_096_),
    .Y(_054_)
  );
  NOR _438_ (
    .A(_054_),
    .B(_053_),
    .Y(_055_)
  );
  NOR _439_ (
    .A(_055_),
    .B(_104_),
    .Y(_056_)
  );
  NAND _440_ (
    .A(_056_),
    .B(_052_),
    .Y(_057_)
  );
  NOT _441_ (
    .A(_323_),
    .Y(_058_)
  );
  NAND _442_ (
    .A(_058_),
    .B(_057_),
    .Y(_059_)
  );
  NAND _443_ (
    .A(_298_),
    .B(_297_),
    .Y(_060_)
  );
  NOR _444_ (
    .A(_060_),
    .B(_327_),
    .Y(_061_)
  );
  NOT _445_ (
    .A(_011_),
    .Y(_062_)
  );
  NOR _446_ (
    .A(_062_),
    .B(_061_),
    .Y(_063_)
  );
  NAND _447_ (
    .A(_303_),
    .B(_302_),
    .Y(_064_)
  );
  NOR _448_ (
    .A(_015_),
    .B(_064_),
    .Y(_065_)
  );
  NAND _449_ (
    .A(_065_),
    .B(_305_),
    .Y(_066_)
  );
  NOR _450_ (
    .A(_066_),
    .B(_063_),
    .Y(_067_)
  );
  NOT _451_ (
    .A(_022_),
    .Y(_068_)
  );
  NAND _452_ (
    .A(_019_),
    .B(_016_),
    .Y(_069_)
  );
  NOR _453_ (
    .A(_069_),
    .B(_068_),
    .Y(_070_)
  );
  NOT _454_ (
    .A(_032_),
    .Y(_071_)
  );
  NOR _455_ (
    .A(_071_),
    .B(_070_),
    .Y(_072_)
  );
  NOT _456_ (
    .A(_043_),
    .Y(_073_)
  );
  NOR _457_ (
    .A(_073_),
    .B(_036_),
    .Y(_074_)
  );
  NOR _458_ (
    .A(_035_),
    .B(_038_),
    .Y(_075_)
  );
  NAND _459_ (
    .A(_075_),
    .B(_074_),
    .Y(_077_)
  );
  NOR _460_ (
    .A(_077_),
    .B(_072_),
    .Y(_079_)
  );
  NAND _461_ (
    .A(_079_),
    .B(_067_),
    .Y(_081_)
  );
  NOR _462_ (
    .A(_081_),
    .B(_059_),
    .Y(_083_)
  );
  NAND _463_ (
    .A(_083_),
    .B(_211_),
    .Y(_085_)
  );
  NAND _464_ (
    .A(_085_),
    .B(_051_),
    .Y(_088_)
  );
  NAND _465_ (
    .A(_088_),
    .B(_306_),
    .Y(_090_)
  );
  NOR _466_ (
    .A(_085_),
    .B(_051_),
    .Y(_092_)
  );
  NOR _467_ (
    .A(_092_),
    .B(_090_),
    .Y(_287_)
  );
  NOT _468_ (
    .A(_284_),
    .Y(_095_)
  );
  NAND _469_ (
    .A(_049_),
    .B(_004_),
    .Y(_097_)
  );
  NAND _470_ (
    .A(_097_),
    .B(_095_),
    .Y(_098_)
  );
  NAND _471_ (
    .A(_098_),
    .B(_306_),
    .Y(_100_)
  );
  NOR _472_ (
    .A(_097_),
    .B(_095_),
    .Y(_101_)
  );
  NOR _473_ (
    .A(_101_),
    .B(_100_),
    .Y(_288_)
  );
  NOR _474_ (
    .A(_101_),
    .B(_299_),
    .Y(_103_)
  );
  NOT _475_ (
    .A(_299_),
    .Y(_105_)
  );
  NOR _476_ (
    .A(_105_),
    .B(_095_),
    .Y(_106_)
  );
  NAND _477_ (
    .A(_106_),
    .B(_092_),
    .Y(_108_)
  );
  NAND _478_ (
    .A(_108_),
    .B(_306_),
    .Y(_109_)
  );
  NOR _479_ (
    .A(_109_),
    .B(_103_),
    .Y(_289_)
  );
  NOT _480_ (
    .A(_005_),
    .Y(_111_)
  );
  NAND _481_ (
    .A(_108_),
    .B(_111_),
    .Y(_113_)
  );
  NAND _482_ (
    .A(_113_),
    .B(_306_),
    .Y(_114_)
  );
  NOR _483_ (
    .A(_108_),
    .B(_111_),
    .Y(_116_)
  );
  NOR _484_ (
    .A(_116_),
    .B(_114_),
    .Y(_290_)
  );
  NOT _485_ (
    .A(_050_),
    .Y(_118_)
  );
  NOT _486_ (
    .A(_106_),
    .Y(_119_)
  );
  NOR _487_ (
    .A(_119_),
    .B(_097_),
    .Y(_121_)
  );
  NAND _488_ (
    .A(_121_),
    .B(_005_),
    .Y(_122_)
  );
  NAND _489_ (
    .A(_122_),
    .B(_118_),
    .Y(_123_)
  );
  NAND _490_ (
    .A(_123_),
    .B(_306_),
    .Y(_124_)
  );
  NOR _491_ (
    .A(_122_),
    .B(_118_),
    .Y(_125_)
  );
  NOR _492_ (
    .A(_125_),
    .B(_124_),
    .Y(_291_)
  );
  NOT _493_ (
    .A(_086_),
    .Y(_126_)
  );
  NAND _494_ (
    .A(_116_),
    .B(_050_),
    .Y(_128_)
  );
  NAND _495_ (
    .A(_128_),
    .B(_126_),
    .Y(_129_)
  );
  NAND _496_ (
    .A(_129_),
    .B(_306_),
    .Y(_130_)
  );
  NOR _497_ (
    .A(_128_),
    .B(_126_),
    .Y(_131_)
  );
  NOR _498_ (
    .A(_131_),
    .B(_130_),
    .Y(_292_)
  );
  NOT _499_ (
    .A(_127_),
    .Y(_132_)
  );
  NAND _500_ (
    .A(_125_),
    .B(_086_),
    .Y(_133_)
  );
  NAND _501_ (
    .A(_133_),
    .B(_132_),
    .Y(_134_)
  );
  NAND _502_ (
    .A(_134_),
    .B(_306_),
    .Y(_135_)
  );
  NOR _503_ (
    .A(_133_),
    .B(_132_),
    .Y(_136_)
  );
  NOR _504_ (
    .A(_136_),
    .B(_135_),
    .Y(_293_)
  );
  NOT _505_ (
    .A(_162_),
    .Y(_137_)
  );
  NAND _506_ (
    .A(_131_),
    .B(_127_),
    .Y(_138_)
  );
  NAND _507_ (
    .A(_138_),
    .B(_137_),
    .Y(_139_)
  );
  NAND _508_ (
    .A(_139_),
    .B(_306_),
    .Y(_140_)
  );
  NAND _509_ (
    .A(_136_),
    .B(_162_),
    .Y(_142_)
  );
  NOT _510_ (
    .A(_142_),
    .Y(_144_)
  );
  NOR _511_ (
    .A(_144_),
    .B(_140_),
    .Y(_294_)
  );
  NOT _512_ (
    .A(_183_),
    .Y(_147_)
  );
  NOR _513_ (
    .A(_142_),
    .B(_147_),
    .Y(_149_)
  );
  NAND _514_ (
    .A(_142_),
    .B(_147_),
    .Y(_151_)
  );
  NAND _515_ (
    .A(_151_),
    .B(_306_),
    .Y(_153_)
  );
  NOR _516_ (
    .A(_153_),
    .B(_149_),
    .Y(_295_)
  );
  NOR _517_ (
    .A(_044_),
    .B(_059_),
    .Y(_156_)
  );
  NOR _518_ (
    .A(_156_),
    .B(_296_),
    .Y(_158_)
  );
  NAND _519_ (
    .A(_046_),
    .B(_306_),
    .Y(_159_)
  );
  NOR _520_ (
    .A(_159_),
    .B(_158_),
    .Y(_320_)
  );
  NAND _521_ (
    .A(_297_),
    .B(_306_),
    .Y(_160_)
  );
  NOR _522_ (
    .A(_160_),
    .B(_156_),
    .Y(_322_)
  );
  NAND _523_ (
    .A(_298_),
    .B(_306_),
    .Y(_161_)
  );
  NOR _524_ (
    .A(_161_),
    .B(_156_),
    .Y(_324_)
  );
  NAND _525_ (
    .A(_300_),
    .B(_306_),
    .Y(_163_)
  );
  NOR _526_ (
    .A(_163_),
    .B(_156_),
    .Y(_326_)
  );
  NAND _527_ (
    .A(_301_),
    .B(_306_),
    .Y(_164_)
  );
  NOR _528_ (
    .A(_164_),
    .B(_156_),
    .Y(_328_)
  );
  NAND _529_ (
    .A(_302_),
    .B(_306_),
    .Y(_165_)
  );
  NOR _530_ (
    .A(_165_),
    .B(_156_),
    .Y(_006_)
  );
  NAND _531_ (
    .A(_303_),
    .B(_306_),
    .Y(_166_)
  );
  NOR _532_ (
    .A(_166_),
    .B(_156_),
    .Y(_008_)
  );
  NAND _533_ (
    .A(_304_),
    .B(_306_),
    .Y(_167_)
  );
  NOR _534_ (
    .A(_167_),
    .B(_156_),
    .Y(_010_)
  );
  NAND _535_ (
    .A(_305_),
    .B(_306_),
    .Y(_168_)
  );
  NOR _536_ (
    .A(_168_),
    .B(_156_),
    .Y(_012_)
  );
  NAND _537_ (
    .A(_307_),
    .B(_306_),
    .Y(_169_)
  );
  NOR _538_ (
    .A(_169_),
    .B(_156_),
    .Y(_014_)
  );
  NOR _539_ (
    .A(_045_),
    .B(_059_),
    .Y(_170_)
  );
  NOR _540_ (
    .A(_170_),
    .B(_026_),
    .Y(_171_)
  );
  NOR _541_ (
    .A(_079_),
    .B(_059_),
    .Y(_172_)
  );
  NOT _542_ (
    .A(_172_),
    .Y(_173_)
  );
  NOR _543_ (
    .A(_173_),
    .B(_016_),
    .Y(_174_)
  );
  NOR _544_ (
    .A(_174_),
    .B(_171_),
    .Y(_175_)
  );
  NOR _545_ (
    .A(_175_),
    .B(_285_),
    .Y(_076_)
  );
  NOR _546_ (
    .A(_173_),
    .B(_026_),
    .Y(_176_)
  );
  NOR _547_ (
    .A(_176_),
    .B(_019_),
    .Y(_177_)
  );
  NAND _548_ (
    .A(_044_),
    .B(_069_),
    .Y(_178_)
  );
  NAND _549_ (
    .A(_178_),
    .B(_170_),
    .Y(_179_)
  );
  NAND _550_ (
    .A(_179_),
    .B(_306_),
    .Y(_180_)
  );
  NOR _551_ (
    .A(_180_),
    .B(_177_),
    .Y(_078_)
  );
  NOR _552_ (
    .A(_179_),
    .B(_068_),
    .Y(_181_)
  );
  NAND _553_ (
    .A(_172_),
    .B(_029_),
    .Y(_182_)
  );
  NAND _554_ (
    .A(_182_),
    .B(_068_),
    .Y(_184_)
  );
  NAND _555_ (
    .A(_184_),
    .B(_306_),
    .Y(_185_)
  );
  NOR _556_ (
    .A(_185_),
    .B(_181_),
    .Y(_080_)
  );
  NOT _557_ (
    .A(_025_),
    .Y(_186_)
  );
  NOR _558_ (
    .A(_170_),
    .B(_186_),
    .Y(_187_)
  );
  NOR _559_ (
    .A(_030_),
    .B(_186_),
    .Y(_188_)
  );
  NOR _560_ (
    .A(_188_),
    .B(_079_),
    .Y(_189_)
  );
  NOR _561_ (
    .A(_189_),
    .B(_187_),
    .Y(_190_)
  );
  NAND _562_ (
    .A(_070_),
    .B(_325_),
    .Y(_191_)
  );
  NAND _563_ (
    .A(_191_),
    .B(_186_),
    .Y(_192_)
  );
  NAND _564_ (
    .A(_192_),
    .B(_306_),
    .Y(_193_)
  );
  NOR _565_ (
    .A(_193_),
    .B(_190_),
    .Y(_082_)
  );
  NAND _566_ (
    .A(_188_),
    .B(_028_),
    .Y(_194_)
  );
  NOT _567_ (
    .A(_194_),
    .Y(_195_)
  );
  NOR _568_ (
    .A(_195_),
    .B(_079_),
    .Y(_196_)
  );
  NOT _569_ (
    .A(_028_),
    .Y(_197_)
  );
  NOR _570_ (
    .A(_170_),
    .B(_197_),
    .Y(_198_)
  );
  NOR _571_ (
    .A(_198_),
    .B(_196_),
    .Y(_199_)
  );
  NAND _572_ (
    .A(_188_),
    .B(_325_),
    .Y(_200_)
  );
  NAND _573_ (
    .A(_200_),
    .B(_197_),
    .Y(_201_)
  );
  NAND _574_ (
    .A(_201_),
    .B(_306_),
    .Y(_202_)
  );
  NOR _575_ (
    .A(_202_),
    .B(_199_),
    .Y(_084_)
  );
  NOR _576_ (
    .A(_194_),
    .B(_173_),
    .Y(_203_)
  );
  NOR _577_ (
    .A(_203_),
    .B(_031_),
    .Y(_204_)
  );
  NOT _578_ (
    .A(_156_),
    .Y(_205_)
  );
  NOR _579_ (
    .A(_205_),
    .B(_067_),
    .Y(_206_)
  );
  NOR _580_ (
    .A(_206_),
    .B(_285_),
    .Y(_207_)
  );
  NAND _581_ (
    .A(_195_),
    .B(_031_),
    .Y(_208_)
  );
  NOT _582_ (
    .A(_208_),
    .Y(_209_)
  );
  NAND _583_ (
    .A(_209_),
    .B(_172_),
    .Y(_210_)
  );
  NAND _584_ (
    .A(_210_),
    .B(_207_),
    .Y(_212_)
  );
  NOR _585_ (
    .A(_212_),
    .B(_204_),
    .Y(_087_)
  );
  NOR _586_ (
    .A(_194_),
    .B(_035_),
    .Y(_213_)
  );
  NOR _587_ (
    .A(_213_),
    .B(_079_),
    .Y(_214_)
  );
  NOT _588_ (
    .A(_034_),
    .Y(_215_)
  );
  NOR _589_ (
    .A(_170_),
    .B(_215_),
    .Y(_216_)
  );
  NOR _590_ (
    .A(_216_),
    .B(_214_),
    .Y(_217_)
  );
  NAND _591_ (
    .A(_209_),
    .B(_325_),
    .Y(_218_)
  );
  NAND _592_ (
    .A(_218_),
    .B(_215_),
    .Y(_219_)
  );
  NAND _593_ (
    .A(_219_),
    .B(_306_),
    .Y(_220_)
  );
  NOR _594_ (
    .A(_220_),
    .B(_217_),
    .Y(_089_)
  );
  NOT _595_ (
    .A(_207_),
    .Y(_221_)
  );
  NOT _596_ (
    .A(_213_),
    .Y(_222_)
  );
  NOR _597_ (
    .A(_222_),
    .B(_036_),
    .Y(_223_)
  );
  NAND _598_ (
    .A(_223_),
    .B(_172_),
    .Y(_224_)
  );
  NAND _599_ (
    .A(_213_),
    .B(_172_),
    .Y(_225_)
  );
  NAND _600_ (
    .A(_225_),
    .B(_036_),
    .Y(_226_)
  );
  NAND _601_ (
    .A(_226_),
    .B(_224_),
    .Y(_227_)
  );
  NOR _602_ (
    .A(_227_),
    .B(_221_),
    .Y(_091_)
  );
  NAND _603_ (
    .A(_223_),
    .B(_325_),
    .Y(_228_)
  );
  NAND _604_ (
    .A(_228_),
    .B(_038_),
    .Y(_229_)
  );
  NAND _605_ (
    .A(_229_),
    .B(_207_),
    .Y(_230_)
  );
  NAND _606_ (
    .A(_223_),
    .B(_040_),
    .Y(_231_)
  );
  NOR _607_ (
    .A(_231_),
    .B(_173_),
    .Y(_232_)
  );
  NOR _608_ (
    .A(_232_),
    .B(_230_),
    .Y(_093_)
  );
  NAND _609_ (
    .A(_205_),
    .B(_043_),
    .Y(_233_)
  );
  NAND _610_ (
    .A(_233_),
    .B(_046_),
    .Y(_234_)
  );
  NOR _611_ (
    .A(_234_),
    .B(_232_),
    .Y(_235_)
  );
  NOR _612_ (
    .A(_235_),
    .B(_285_),
    .Y(_094_)
  );
  NOR _613_ (
    .A(_156_),
    .B(_310_),
    .Y(_236_)
  );
  NAND _614_ (
    .A(_325_),
    .B(_310_),
    .Y(_237_)
  );
  NAND _615_ (
    .A(_237_),
    .B(_306_),
    .Y(_238_)
  );
  NOR _616_ (
    .A(_238_),
    .B(_236_),
    .Y(_141_)
  );
  NOR _617_ (
    .A(_205_),
    .B(_311_),
    .Y(_239_)
  );
  NOR _618_ (
    .A(_325_),
    .B(_312_),
    .Y(_240_)
  );
  NOR _619_ (
    .A(_240_),
    .B(_239_),
    .Y(_241_)
  );
  NAND _620_ (
    .A(_311_),
    .B(_310_),
    .Y(_242_)
  );
  NAND _621_ (
    .A(_242_),
    .B(_306_),
    .Y(_243_)
  );
  NOR _622_ (
    .A(_243_),
    .B(_241_),
    .Y(_143_)
  );
  NOR _623_ (
    .A(_205_),
    .B(_053_),
    .Y(_244_)
  );
  NOR _624_ (
    .A(_325_),
    .B(_055_),
    .Y(_245_)
  );
  NOR _625_ (
    .A(_245_),
    .B(_244_),
    .Y(_246_)
  );
  NAND _626_ (
    .A(_054_),
    .B(_053_),
    .Y(_247_)
  );
  NAND _627_ (
    .A(_247_),
    .B(_306_),
    .Y(_248_)
  );
  NOR _628_ (
    .A(_248_),
    .B(_246_),
    .Y(_145_)
  );
  NOR _629_ (
    .A(_205_),
    .B(_309_),
    .Y(_249_)
  );
  NOR _630_ (
    .A(_313_),
    .B(_309_),
    .Y(_250_)
  );
  NAND _631_ (
    .A(_323_),
    .B(_314_),
    .Y(_251_)
  );
  NOR _632_ (
    .A(_251_),
    .B(_250_),
    .Y(_252_)
  );
  NOR _633_ (
    .A(_252_),
    .B(_249_),
    .Y(_253_)
  );
  NOR _634_ (
    .A(_253_),
    .B(_285_),
    .Y(_146_)
  );
  NOR _635_ (
    .A(_205_),
    .B(_052_),
    .Y(_254_)
  );
  NOT _636_ (
    .A(_250_),
    .Y(_255_)
  );
  NOR _637_ (
    .A(_255_),
    .B(_052_),
    .Y(_256_)
  );
  NOR _638_ (
    .A(_256_),
    .B(_325_),
    .Y(_257_)
  );
  NOR _639_ (
    .A(_257_),
    .B(_254_),
    .Y(_258_)
  );
  NAND _640_ (
    .A(_255_),
    .B(_052_),
    .Y(_259_)
  );
  NAND _641_ (
    .A(_259_),
    .B(_306_),
    .Y(_260_)
  );
  NOR _642_ (
    .A(_260_),
    .B(_258_),
    .Y(_148_)
  );
  NAND _643_ (
    .A(_256_),
    .B(_323_),
    .Y(_261_)
  );
  NOR _644_ (
    .A(_261_),
    .B(_316_),
    .Y(_262_)
  );
  NAND _645_ (
    .A(_173_),
    .B(_110_),
    .Y(_263_)
  );
  NAND _646_ (
    .A(_263_),
    .B(_261_),
    .Y(_264_)
  );
  NAND _647_ (
    .A(_264_),
    .B(_306_),
    .Y(_265_)
  );
  NOR _648_ (
    .A(_265_),
    .B(_262_),
    .Y(_150_)
  );
  NOT _649_ (
    .A(_112_),
    .Y(_266_)
  );
  NOR _650_ (
    .A(_172_),
    .B(_266_),
    .Y(_267_)
  );
  NOR _651_ (
    .A(_267_),
    .B(_262_),
    .Y(_268_)
  );
  NAND _652_ (
    .A(_262_),
    .B(_112_),
    .Y(_269_)
  );
  NAND _653_ (
    .A(_269_),
    .B(_306_),
    .Y(_270_)
  );
  NOR _654_ (
    .A(_270_),
    .B(_268_),
    .Y(_152_)
  );
  NAND _655_ (
    .A(_256_),
    .B(_318_),
    .Y(_271_)
  );
  NOR _656_ (
    .A(_271_),
    .B(_058_),
    .Y(_272_)
  );
  NAND _657_ (
    .A(_173_),
    .B(_115_),
    .Y(_273_)
  );
  NAND _658_ (
    .A(_273_),
    .B(_269_),
    .Y(_274_)
  );
  NAND _659_ (
    .A(_274_),
    .B(_306_),
    .Y(_275_)
  );
  NOR _660_ (
    .A(_275_),
    .B(_272_),
    .Y(_154_)
  );
  NAND _661_ (
    .A(_173_),
    .B(_306_),
    .Y(_276_)
  );
  NOT _662_ (
    .A(_271_),
    .Y(_277_)
  );
  NOR _663_ (
    .A(_277_),
    .B(_117_),
    .Y(_278_)
  );
  NOT _664_ (
    .A(_117_),
    .Y(_279_)
  );
  NOR _665_ (
    .A(_271_),
    .B(_279_),
    .Y(_280_)
  );
  NOR _666_ (
    .A(_280_),
    .B(_278_),
    .Y(_281_)
  );
  NOR _667_ (
    .A(_281_),
    .B(_325_),
    .Y(_282_)
  );
  NOR _668_ (
    .A(_282_),
    .B(_276_),
    .Y(_155_)
  );
  NOR _669_ (
    .A(_280_),
    .B(_120_),
    .Y(_283_)
  );
  NOR _670_ (
    .A(_283_),
    .B(_276_),
    .Y(_157_)
  );
  DFF _671_ (
    .C(CLK),
    .D(_002_[0]),
    .Q(nanos[0])
  );
  DFF _672_ (
    .C(CLK),
    .D(_002_[1]),
    .Q(nanos[1])
  );
  DFF _673_ (
    .C(CLK),
    .D(_002_[2]),
    .Q(nanos[2])
  );
  DFF _674_ (
    .C(CLK),
    .D(_002_[3]),
    .Q(nanos[3])
  );
  DFF _675_ (
    .C(CLK),
    .D(_002_[4]),
    .Q(nanos[4])
  );
  DFF _676_ (
    .C(CLK),
    .D(_002_[5]),
    .Q(nanos[5])
  );
  DFF _677_ (
    .C(CLK),
    .D(_002_[6]),
    .Q(nanos[6])
  );
  DFF _678_ (
    .C(CLK),
    .D(_002_[7]),
    .Q(nanos[7])
  );
  DFF _679_ (
    .C(CLK),
    .D(_002_[8]),
    .Q(nanos[8])
  );
  DFF _680_ (
    .C(CLK),
    .D(_002_[9]),
    .Q(nanos[9])
  );
  DFF _681_ (
    .C(CLK),
    .D(_000_[0]),
    .Q(micros[0])
  );
  DFF _682_ (
    .C(CLK),
    .D(_000_[1]),
    .Q(micros[1])
  );
  DFF _683_ (
    .C(CLK),
    .D(_000_[2]),
    .Q(micros[2])
  );
  DFF _684_ (
    .C(CLK),
    .D(_000_[3]),
    .Q(micros[3])
  );
  DFF _685_ (
    .C(CLK),
    .D(_000_[4]),
    .Q(micros[4])
  );
  DFF _686_ (
    .C(CLK),
    .D(_000_[5]),
    .Q(micros[5])
  );
  DFF _687_ (
    .C(CLK),
    .D(_000_[6]),
    .Q(micros[6])
  );
  DFF _688_ (
    .C(CLK),
    .D(_000_[7]),
    .Q(micros[7])
  );
  DFF _689_ (
    .C(CLK),
    .D(_000_[8]),
    .Q(micros[8])
  );
  DFF _690_ (
    .C(CLK),
    .D(_000_[9]),
    .Q(micros[9])
  );
  DFF _691_ (
    .C(CLK),
    .D(_001_[0]),
    .Q(milis[0])
  );
  DFF _692_ (
    .C(CLK),
    .D(_001_[1]),
    .Q(milis[1])
  );
  DFF _693_ (
    .C(CLK),
    .D(_001_[2]),
    .Q(milis[2])
  );
  DFF _694_ (
    .C(CLK),
    .D(_001_[3]),
    .Q(milis[3])
  );
  DFF _695_ (
    .C(CLK),
    .D(_001_[4]),
    .Q(milis[4])
  );
  DFF _696_ (
    .C(CLK),
    .D(_001_[5]),
    .Q(milis[5])
  );
  DFF _697_ (
    .C(CLK),
    .D(_001_[6]),
    .Q(milis[6])
  );
  DFF _698_ (
    .C(CLK),
    .D(_001_[7]),
    .Q(milis[7])
  );
  DFF _699_ (
    .C(CLK),
    .D(_001_[8]),
    .Q(milis[8])
  );
  DFF _700_ (
    .C(CLK),
    .D(_001_[9]),
    .Q(milis[9])
  );
  DFF _701_ (
    .C(CLK),
    .D(_003_[0]),
    .Q(segs[0])
  );
  DFF _702_ (
    .C(CLK),
    .D(_003_[1]),
    .Q(segs[1])
  );
  DFF _703_ (
    .C(CLK),
    .D(_003_[2]),
    .Q(segs[2])
  );
  DFF _704_ (
    .C(CLK),
    .D(_003_[3]),
    .Q(segs[3])
  );
  DFF _705_ (
    .C(CLK),
    .D(_003_[4]),
    .Q(segs[4])
  );
  DFF _706_ (
    .C(CLK),
    .D(_003_[5]),
    .Q(segs[5])
  );
  DFF _707_ (
    .C(CLK),
    .D(_003_[6]),
    .Q(segs[6])
  );
  DFF _708_ (
    .C(CLK),
    .D(_003_[7]),
    .Q(segs[7])
  );
  DFF _709_ (
    .C(CLK),
    .D(_003_[8]),
    .Q(segs[8])
  );
  DFF _710_ (
    .C(CLK),
    .D(_003_[9]),
    .Q(segs[9])
  );
  assign _004_ = segs[1];
  assign _284_ = segs[2];
  assign _299_ = segs[3];
  assign _005_ = segs[4];
  assign _050_ = segs[5];
  assign _086_ = segs[6];
  assign _127_ = segs[7];
  assign _162_ = segs[8];
  assign _183_ = segs[9];
  assign _211_ = segs[0];
  assign _285_ = reset;
  assign _003_[0] = _286_;
  assign _003_[1] = _287_;
  assign _003_[2] = _288_;
  assign _003_[3] = _289_;
  assign _003_[4] = _290_;
  assign _003_[5] = _291_;
  assign _003_[6] = _292_;
  assign _003_[7] = _293_;
  assign _003_[8] = _294_;
  assign _003_[9] = _295_;
  assign _296_ = milis[0];
  assign _297_ = milis[1];
  assign _298_ = milis[2];
  assign _300_ = milis[3];
  assign _301_ = milis[4];
  assign _302_ = milis[5];
  assign _303_ = milis[6];
  assign _304_ = milis[7];
  assign _305_ = milis[8];
  assign _307_ = milis[9];
  assign _001_[0] = _320_;
  assign _001_[1] = _322_;
  assign _001_[2] = _324_;
  assign _001_[3] = _326_;
  assign _001_[4] = _328_;
  assign _001_[5] = _006_;
  assign _001_[6] = _008_;
  assign _001_[7] = _010_;
  assign _001_[8] = _012_;
  assign _001_[9] = _014_;
  assign _016_ = micros[0];
  assign _019_ = micros[1];
  assign _022_ = micros[2];
  assign _025_ = micros[3];
  assign _028_ = micros[4];
  assign _031_ = micros[5];
  assign _034_ = micros[6];
  assign _037_ = micros[7];
  assign _040_ = micros[8];
  assign _043_ = micros[9];
  assign _000_[0] = _076_;
  assign _000_[1] = _078_;
  assign _000_[2] = _080_;
  assign _000_[3] = _082_;
  assign _000_[4] = _084_;
  assign _000_[5] = _087_;
  assign _000_[6] = _089_;
  assign _000_[7] = _091_;
  assign _000_[8] = _093_;
  assign _000_[9] = _094_;
  assign _096_ = nanos[0];
  assign _099_ = nanos[1];
  assign _102_ = nanos[2];
  assign _104_ = nanos[3];
  assign _107_ = nanos[4];
  assign _110_ = nanos[5];
  assign _112_ = nanos[6];
  assign _115_ = nanos[7];
  assign _117_ = nanos[8];
  assign _120_ = nanos[9];
  assign _002_[0] = _141_;
  assign _002_[1] = _143_;
  assign _002_[2] = _145_;
  assign _002_[3] = _146_;
  assign _002_[4] = _148_;
  assign _002_[5] = _150_;
  assign _002_[6] = _152_;
  assign _002_[7] = _154_;
  assign _002_[8] = _155_;
  assign _002_[9] = _157_;
endmodule
