/* Generated by Yosys 0.7 (git sha1 UNKNOWN, gcc 4.9.2-10 -fPIC -Os) */

`include "cmos_cells.v"

(* src = "Rx_Module.v:23" *)
module Rx_Module(CLK, reset, Start, iRX_BUF_FRAME_TYPE, iALERT, iRECEIVE_DETECT, iRECEIVE_BYTE_COUNT, Tx_State_Machine_ACTIVE, Unexpected_GoodCRC, CC_Busy, CC_IDLE, Data_In, oALERT, oRECEIVE_BYTE_COUNT, oGoodCRC_to_PHY, oDIR_WRITE, oDATA_to_Buffer);
  (* src = "Rx_Module.v:83" *)
  wire [15:0] _000_;
  (* src = "Rx_Module.v:83" *)
  wire [7:0] _001_;
  (* src = "Rx_Module.v:83" *)
  wire [7:0] _002_;
  (* src = "Rx_Module.v:83" *)
  wire _003_;
  (* src = "Rx_Module.v:83" *)
  wire [7:0] _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  (* src = "Rx_Module.v:178" *)
  wire [7:0] _312_;
  (* src = "Rx_Module.v:180" *)
  wire [31:0] _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire [4:0] _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire [1:0] _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire [2:0] _343_;
  wire [1:0] _344_;
  wire [1:0] _345_;
  wire [1:0] _346_;
  wire [2:0] _347_;
  wire [1:0] _348_;
  wire _349_;
  wire _350_;
  wire _351_;
  wire _352_;
  wire _353_;
  wire _354_;
  (* src = "Rx_Module.v:71" *)
  wire _355_;
  (* src = "Rx_Module.v:116" *)
  wire _356_;
  (* src = "Rx_Module.v:116" *)
  wire _357_;
  (* src = "Rx_Module.v:116" *)
  wire _358_;
  (* src = "Rx_Module.v:163" *)
  wire _359_;
  (* src = "Rx_Module.v:163" *)
  wire _360_;
  (* src = "Rx_Module.v:112|<techmap.v>:432" *)
  wire [15:0] _361_;
  (* src = "Rx_Module.v:112|<techmap.v>:428" *)
  wire [7:0] _362_;
  wire [7:0] _363_;
  (* src = "Rx_Module.v:112|<techmap.v>:432" *)
  wire [31:0] _364_;
  (* src = "Rx_Module.v:112|<techmap.v>:428" *)
  wire [15:0] _365_;
  wire [15:0] _366_;
  (* src = "<techmap.v>:260|<techmap.v>:203" *)
  wire [7:0] _367_;
  wire [7:0] _368_;
  (* src = "<techmap.v>:260|<techmap.v>:203" *)
  wire [31:0] _369_;
  (* src = "Rx_Module.v:112|<techmap.v>:445" *)
  wire _370_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _371_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _372_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _373_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _374_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _375_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _376_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _377_;
  (* src = "Rx_Module.v:42" *)
  input CC_Busy;
  (* src = "Rx_Module.v:42" *)
  input CC_IDLE;
  (* src = "Rx_Module.v:43" *)
  input CLK;
  (* src = "Rx_Module.v:44" *)
  input [7:0] Data_In;
  (* src = "Rx_Module.v:68" *)
  wire PHY_Reset;
  (* src = "Rx_Module.v:50" *)
  input Start;
  (* src = "Rx_Module.v:51" *)
  input Tx_State_Machine_ACTIVE;
  (* src = "Rx_Module.v:52" *)
  input Unexpected_GoodCRC;
  (* src = "Rx_Module.v:45" *)
  input [15:0] iALERT;
  (* src = "Rx_Module.v:46" *)
  input [7:0] iRECEIVE_BYTE_COUNT;
  (* src = "Rx_Module.v:47" *)
  input [7:0] iRECEIVE_DETECT;
  (* src = "Rx_Module.v:48" *)
  input [7:0] iRX_BUF_FRAME_TYPE;
  (* src = "Rx_Module.v:62" *)
  wire [15:0] nxt_oALERT;
  (* src = "Rx_Module.v:63" *)
  wire [7:0] nxt_oDATA_to_Buffer;
  (* src = "Rx_Module.v:64" *)
  wire [7:0] nxt_oDIR_WRITE;
  (* src = "Rx_Module.v:65" *)
  wire nxt_oGoodCRC_to_PHY;
  (* src = "Rx_Module.v:66" *)
  wire [7:0] nxt_oRECEIVE_BYTE_COUNT;
  (* src = "Rx_Module.v:55" *)
  output [15:0] oALERT;
  (* src = "Rx_Module.v:56" *)
  output [7:0] oDATA_to_Buffer;
  (* src = "Rx_Module.v:57" *)
  output [7:0] oDIR_WRITE;
  (* src = "Rx_Module.v:58" *)
  output oGoodCRC_to_PHY;
  (* src = "Rx_Module.v:59" *)
  output [7:0] oRECEIVE_BYTE_COUNT;
  (* src = "Rx_Module.v:49" *)
  input reset;
  (* onehot = 32'd1 *)
  wire [4:0] state;
  NAND _378_ (
    .A(_279_),
    .B(_277_),
    .Y(_009_)
  );
  NOR _379_ (
    .A(_009_),
    .B(_005_),
    .Y(_010_)
  );
  NOT _380_ (
    .A(_008_),
    .Y(_011_)
  );
  NOT _381_ (
    .A(_013_),
    .Y(_012_)
  );
  NAND _382_ (
    .A(_012_),
    .B(_011_),
    .Y(_014_)
  );
  NOR _383_ (
    .A(_014_),
    .B(_010_),
    .Y(_016_)
  );
  NAND _384_ (
    .A(_016_),
    .B(_280_),
    .Y(_018_)
  );
  NOT _385_ (
    .A(_167_),
    .Y(_019_)
  );
  NAND _386_ (
    .A(_282_),
    .B(_019_),
    .Y(_021_)
  );
  NOR _387_ (
    .A(_021_),
    .B(_006_),
    .Y(_023_)
  );
  NOR _388_ (
    .A(_023_),
    .B(_310_),
    .Y(_025_)
  );
  NAND _389_ (
    .A(_025_),
    .B(_018_),
    .Y(_311_)
  );
  NOT _390_ (
    .A(_280_),
    .Y(_027_)
  );
  NOR _391_ (
    .A(_016_),
    .B(_027_),
    .Y(_029_)
  );
  NOT _392_ (
    .A(_020_),
    .Y(_030_)
  );
  NOR _393_ (
    .A(_017_),
    .B(_015_),
    .Y(_032_)
  );
  NAND _394_ (
    .A(_032_),
    .B(_030_),
    .Y(_034_)
  );
  NAND _395_ (
    .A(_034_),
    .B(_062_),
    .Y(_035_)
  );
  NOT _396_ (
    .A(_282_),
    .Y(_037_)
  );
  NOR _397_ (
    .A(_037_),
    .B(_019_),
    .Y(_039_)
  );
  NOR _398_ (
    .A(_039_),
    .B(_308_),
    .Y(_040_)
  );
  NAND _399_ (
    .A(_040_),
    .B(_035_),
    .Y(_042_)
  );
  NOR _400_ (
    .A(_042_),
    .B(_029_),
    .Y(_044_)
  );
  NOR _401_ (
    .A(_044_),
    .B(_310_),
    .Y(_095_)
  );
  NOT _402_ (
    .A(_308_),
    .Y(_046_)
  );
  NOR _403_ (
    .A(_270_),
    .B(_046_),
    .Y(_048_)
  );
  NOT _404_ (
    .A(_065_),
    .Y(_049_)
  );
  NOT _405_ (
    .A(_309_),
    .Y(_051_)
  );
  NOR _406_ (
    .A(_030_),
    .B(_051_),
    .Y(_053_)
  );
  NOT _407_ (
    .A(_053_),
    .Y(_054_)
  );
  NAND _408_ (
    .A(_051_),
    .B(_308_),
    .Y(_056_)
  );
  NAND _409_ (
    .A(_056_),
    .B(_054_),
    .Y(_058_)
  );
  NOR _410_ (
    .A(_058_),
    .B(_049_),
    .Y(_059_)
  );
  NOR _411_ (
    .A(_059_),
    .B(_048_),
    .Y(_061_)
  );
  NOR _412_ (
    .A(_061_),
    .B(_310_),
    .Y(_123_)
  );
  NOT _413_ (
    .A(_268_),
    .Y(_063_)
  );
  NOT _414_ (
    .A(_270_),
    .Y(_064_)
  );
  NOR _415_ (
    .A(_064_),
    .B(_063_),
    .Y(_066_)
  );
  NAND _416_ (
    .A(_064_),
    .B(_063_),
    .Y(_067_)
  );
  NAND _417_ (
    .A(_067_),
    .B(_308_),
    .Y(_068_)
  );
  NOR _418_ (
    .A(_068_),
    .B(_066_),
    .Y(_070_)
  );
  NOT _419_ (
    .A(_069_),
    .Y(_071_)
  );
  NOR _420_ (
    .A(_058_),
    .B(_071_),
    .Y(_073_)
  );
  NOR _421_ (
    .A(_073_),
    .B(_070_),
    .Y(_074_)
  );
  NOR _422_ (
    .A(_074_),
    .B(_310_),
    .Y(_125_)
  );
  NOT _423_ (
    .A(_266_),
    .Y(_076_)
  );
  NAND _424_ (
    .A(_270_),
    .B(_268_),
    .Y(_078_)
  );
  NOR _425_ (
    .A(_078_),
    .B(_076_),
    .Y(_079_)
  );
  NAND _426_ (
    .A(_078_),
    .B(_076_),
    .Y(_081_)
  );
  NAND _427_ (
    .A(_081_),
    .B(_308_),
    .Y(_082_)
  );
  NOR _428_ (
    .A(_082_),
    .B(_079_),
    .Y(_084_)
  );
  NOT _429_ (
    .A(_072_),
    .Y(_085_)
  );
  NOR _430_ (
    .A(_058_),
    .B(_085_),
    .Y(_087_)
  );
  NOR _431_ (
    .A(_087_),
    .B(_084_),
    .Y(_088_)
  );
  NOR _432_ (
    .A(_088_),
    .B(_310_),
    .Y(_128_)
  );
  NOT _433_ (
    .A(_264_),
    .Y(_090_)
  );
  NAND _434_ (
    .A(_066_),
    .B(_266_),
    .Y(_092_)
  );
  NOR _435_ (
    .A(_092_),
    .B(_090_),
    .Y(_093_)
  );
  NAND _436_ (
    .A(_092_),
    .B(_090_),
    .Y(_094_)
  );
  NAND _437_ (
    .A(_094_),
    .B(_308_),
    .Y(_097_)
  );
  NOR _438_ (
    .A(_097_),
    .B(_093_),
    .Y(_098_)
  );
  NOT _439_ (
    .A(_075_),
    .Y(_099_)
  );
  NOR _440_ (
    .A(_058_),
    .B(_099_),
    .Y(_101_)
  );
  NOR _441_ (
    .A(_101_),
    .B(_098_),
    .Y(_102_)
  );
  NOR _442_ (
    .A(_102_),
    .B(_310_),
    .Y(_131_)
  );
  NOT _443_ (
    .A(_250_),
    .Y(_104_)
  );
  NAND _444_ (
    .A(_079_),
    .B(_264_),
    .Y(_105_)
  );
  NOR _445_ (
    .A(_105_),
    .B(_104_),
    .Y(_106_)
  );
  NAND _446_ (
    .A(_105_),
    .B(_104_),
    .Y(_108_)
  );
  NAND _447_ (
    .A(_108_),
    .B(_308_),
    .Y(_109_)
  );
  NOR _448_ (
    .A(_109_),
    .B(_106_),
    .Y(_110_)
  );
  NOT _449_ (
    .A(_077_),
    .Y(_112_)
  );
  NOR _450_ (
    .A(_058_),
    .B(_112_),
    .Y(_113_)
  );
  NOR _451_ (
    .A(_113_),
    .B(_110_),
    .Y(_114_)
  );
  NOR _452_ (
    .A(_114_),
    .B(_310_),
    .Y(_134_)
  );
  NOT _453_ (
    .A(_080_),
    .Y(_116_)
  );
  NOR _454_ (
    .A(_058_),
    .B(_116_),
    .Y(_117_)
  );
  NOR _455_ (
    .A(_106_),
    .B(_256_),
    .Y(_119_)
  );
  NAND _456_ (
    .A(_106_),
    .B(_256_),
    .Y(_120_)
  );
  NAND _457_ (
    .A(_120_),
    .B(_308_),
    .Y(_121_)
  );
  NOR _458_ (
    .A(_121_),
    .B(_119_),
    .Y(_122_)
  );
  NOR _459_ (
    .A(_122_),
    .B(_117_),
    .Y(_124_)
  );
  NOR _460_ (
    .A(_124_),
    .B(_310_),
    .Y(_137_)
  );
  NOT _461_ (
    .A(_083_),
    .Y(_126_)
  );
  NOR _462_ (
    .A(_058_),
    .B(_126_),
    .Y(_127_)
  );
  NOT _463_ (
    .A(_258_),
    .Y(_129_)
  );
  NOR _464_ (
    .A(_120_),
    .B(_129_),
    .Y(_130_)
  );
  NAND _465_ (
    .A(_120_),
    .B(_129_),
    .Y(_132_)
  );
  NAND _466_ (
    .A(_132_),
    .B(_308_),
    .Y(_133_)
  );
  NOR _467_ (
    .A(_133_),
    .B(_130_),
    .Y(_135_)
  );
  NOR _468_ (
    .A(_135_),
    .B(_127_),
    .Y(_136_)
  );
  NOR _469_ (
    .A(_136_),
    .B(_310_),
    .Y(_139_)
  );
  NOT _470_ (
    .A(_086_),
    .Y(_138_)
  );
  NOR _471_ (
    .A(_058_),
    .B(_138_),
    .Y(_140_)
  );
  NOR _472_ (
    .A(_130_),
    .B(_288_),
    .Y(_141_)
  );
  NAND _473_ (
    .A(_130_),
    .B(_288_),
    .Y(_143_)
  );
  NAND _474_ (
    .A(_143_),
    .B(_308_),
    .Y(_145_)
  );
  NOR _475_ (
    .A(_145_),
    .B(_141_),
    .Y(_147_)
  );
  NOR _476_ (
    .A(_147_),
    .B(_140_),
    .Y(_149_)
  );
  NOR _477_ (
    .A(_149_),
    .B(_310_),
    .Y(_142_)
  );
  NOR _478_ (
    .A(_062_),
    .B(_060_),
    .Y(_152_)
  );
  NOR _479_ (
    .A(_152_),
    .B(_310_),
    .Y(_144_)
  );
  NOT _480_ (
    .A(_091_),
    .Y(_155_)
  );
  NOR _481_ (
    .A(_155_),
    .B(_308_),
    .Y(_157_)
  );
  NOR _482_ (
    .A(_157_),
    .B(_048_),
    .Y(_159_)
  );
  NOR _483_ (
    .A(_159_),
    .B(_310_),
    .Y(_146_)
  );
  NOT _484_ (
    .A(_096_),
    .Y(_162_)
  );
  NOR _485_ (
    .A(_162_),
    .B(_308_),
    .Y(_164_)
  );
  NOR _486_ (
    .A(_164_),
    .B(_070_),
    .Y(_166_)
  );
  NOR _487_ (
    .A(_166_),
    .B(_310_),
    .Y(_148_)
  );
  NOT _488_ (
    .A(_100_),
    .Y(_170_)
  );
  NOR _489_ (
    .A(_170_),
    .B(_308_),
    .Y(_172_)
  );
  NOR _490_ (
    .A(_172_),
    .B(_084_),
    .Y(_174_)
  );
  NOR _491_ (
    .A(_174_),
    .B(_310_),
    .Y(_150_)
  );
  NOT _492_ (
    .A(_103_),
    .Y(_176_)
  );
  NOR _493_ (
    .A(_176_),
    .B(_308_),
    .Y(_177_)
  );
  NOR _494_ (
    .A(_177_),
    .B(_098_),
    .Y(_179_)
  );
  NOR _495_ (
    .A(_179_),
    .B(_310_),
    .Y(_151_)
  );
  NOT _496_ (
    .A(_310_),
    .Y(_181_)
  );
  NOT _497_ (
    .A(_107_),
    .Y(_182_)
  );
  NAND _498_ (
    .A(_182_),
    .B(_046_),
    .Y(_184_)
  );
  NAND _499_ (
    .A(_184_),
    .B(_181_),
    .Y(_185_)
  );
  NOR _500_ (
    .A(_185_),
    .B(_110_),
    .Y(_153_)
  );
  NOR _501_ (
    .A(_108_),
    .B(_256_),
    .Y(_187_)
  );
  NAND _502_ (
    .A(_108_),
    .B(_256_),
    .Y(_189_)
  );
  NAND _503_ (
    .A(_189_),
    .B(_308_),
    .Y(_190_)
  );
  NOR _504_ (
    .A(_190_),
    .B(_187_),
    .Y(_192_)
  );
  NOT _505_ (
    .A(_111_),
    .Y(_193_)
  );
  NAND _506_ (
    .A(_193_),
    .B(_046_),
    .Y(_195_)
  );
  NAND _507_ (
    .A(_195_),
    .B(_181_),
    .Y(_196_)
  );
  NOR _508_ (
    .A(_196_),
    .B(_192_),
    .Y(_154_)
  );
  NOR _509_ (
    .A(_115_),
    .B(_308_),
    .Y(_198_)
  );
  NAND _510_ (
    .A(_187_),
    .B(_129_),
    .Y(_200_)
  );
  NOT _511_ (
    .A(_256_),
    .Y(_201_)
  );
  NOR _512_ (
    .A(_093_),
    .B(_250_),
    .Y(_203_)
  );
  NAND _513_ (
    .A(_203_),
    .B(_201_),
    .Y(_204_)
  );
  NAND _514_ (
    .A(_204_),
    .B(_258_),
    .Y(_206_)
  );
  NAND _515_ (
    .A(_206_),
    .B(_200_),
    .Y(_207_)
  );
  NAND _516_ (
    .A(_207_),
    .B(_308_),
    .Y(_209_)
  );
  NAND _517_ (
    .A(_209_),
    .B(_181_),
    .Y(_210_)
  );
  NOR _518_ (
    .A(_210_),
    .B(_198_),
    .Y(_156_)
  );
  NOR _519_ (
    .A(_187_),
    .B(_129_),
    .Y(_212_)
  );
  NOR _520_ (
    .A(_212_),
    .B(_288_),
    .Y(_214_)
  );
  NOT _521_ (
    .A(_288_),
    .Y(_215_)
  );
  NOR _522_ (
    .A(_206_),
    .B(_215_),
    .Y(_217_)
  );
  NOR _523_ (
    .A(_217_),
    .B(_214_),
    .Y(_219_)
  );
  NOR _524_ (
    .A(_219_),
    .B(_046_),
    .Y(_221_)
  );
  NOT _525_ (
    .A(_118_),
    .Y(_223_)
  );
  NAND _526_ (
    .A(_223_),
    .B(_046_),
    .Y(_225_)
  );
  NAND _527_ (
    .A(_225_),
    .B(_181_),
    .Y(_227_)
  );
  NOR _528_ (
    .A(_227_),
    .B(_221_),
    .Y(_158_)
  );
  NOR _529_ (
    .A(_022_),
    .B(_308_),
    .Y(_230_)
  );
  NOT _530_ (
    .A(_024_),
    .Y(_232_)
  );
  NAND _531_ (
    .A(_232_),
    .B(_308_),
    .Y(_234_)
  );
  NAND _532_ (
    .A(_234_),
    .B(_181_),
    .Y(_236_)
  );
  NOR _533_ (
    .A(_236_),
    .B(_230_),
    .Y(_160_)
  );
  NOR _534_ (
    .A(_026_),
    .B(_308_),
    .Y(_239_)
  );
  NOT _535_ (
    .A(_028_),
    .Y(_241_)
  );
  NAND _536_ (
    .A(_241_),
    .B(_308_),
    .Y(_243_)
  );
  NAND _537_ (
    .A(_243_),
    .B(_181_),
    .Y(_245_)
  );
  NOR _538_ (
    .A(_245_),
    .B(_239_),
    .Y(_161_)
  );
  NOR _539_ (
    .A(_031_),
    .B(_308_),
    .Y(_246_)
  );
  NOT _540_ (
    .A(_033_),
    .Y(_247_)
  );
  NAND _541_ (
    .A(_247_),
    .B(_308_),
    .Y(_249_)
  );
  NAND _542_ (
    .A(_249_),
    .B(_181_),
    .Y(_251_)
  );
  NOR _543_ (
    .A(_251_),
    .B(_246_),
    .Y(_163_)
  );
  NOR _544_ (
    .A(_036_),
    .B(_308_),
    .Y(_252_)
  );
  NOT _545_ (
    .A(_038_),
    .Y(_253_)
  );
  NAND _546_ (
    .A(_253_),
    .B(_308_),
    .Y(_254_)
  );
  NAND _547_ (
    .A(_254_),
    .B(_181_),
    .Y(_255_)
  );
  NOR _548_ (
    .A(_255_),
    .B(_252_),
    .Y(_165_)
  );
  NOR _549_ (
    .A(_041_),
    .B(_308_),
    .Y(_257_)
  );
  NOT _550_ (
    .A(_043_),
    .Y(_259_)
  );
  NAND _551_ (
    .A(_259_),
    .B(_308_),
    .Y(_260_)
  );
  NAND _552_ (
    .A(_260_),
    .B(_181_),
    .Y(_261_)
  );
  NOR _553_ (
    .A(_261_),
    .B(_257_),
    .Y(_168_)
  );
  NOR _554_ (
    .A(_045_),
    .B(_308_),
    .Y(_262_)
  );
  NOT _555_ (
    .A(_047_),
    .Y(_263_)
  );
  NAND _556_ (
    .A(_263_),
    .B(_308_),
    .Y(_265_)
  );
  NAND _557_ (
    .A(_265_),
    .B(_181_),
    .Y(_267_)
  );
  NOR _558_ (
    .A(_267_),
    .B(_262_),
    .Y(_169_)
  );
  NOR _559_ (
    .A(_050_),
    .B(_308_),
    .Y(_269_)
  );
  NOT _560_ (
    .A(_052_),
    .Y(_271_)
  );
  NAND _561_ (
    .A(_271_),
    .B(_308_),
    .Y(_272_)
  );
  NAND _562_ (
    .A(_272_),
    .B(_181_),
    .Y(_273_)
  );
  NOR _563_ (
    .A(_273_),
    .B(_269_),
    .Y(_171_)
  );
  NOR _564_ (
    .A(_055_),
    .B(_308_),
    .Y(_274_)
  );
  NOT _565_ (
    .A(_057_),
    .Y(_275_)
  );
  NAND _566_ (
    .A(_275_),
    .B(_308_),
    .Y(_276_)
  );
  NAND _567_ (
    .A(_276_),
    .B(_181_),
    .Y(_278_)
  );
  NOR _568_ (
    .A(_278_),
    .B(_274_),
    .Y(_173_)
  );
  NOT _569_ (
    .A(_218_),
    .Y(_281_)
  );
  NOR _570_ (
    .A(_281_),
    .B(_310_),
    .Y(_175_)
  );
  NOT _571_ (
    .A(_220_),
    .Y(_284_)
  );
  NOR _572_ (
    .A(_284_),
    .B(_310_),
    .Y(_178_)
  );
  NOR _573_ (
    .A(_222_),
    .B(_308_),
    .Y(_286_)
  );
  NOR _574_ (
    .A(_286_),
    .B(_310_),
    .Y(_180_)
  );
  NOT _575_ (
    .A(_224_),
    .Y(_287_)
  );
  NOR _576_ (
    .A(_287_),
    .B(_310_),
    .Y(_183_)
  );
  NOT _577_ (
    .A(_226_),
    .Y(_289_)
  );
  NOR _578_ (
    .A(_289_),
    .B(_310_),
    .Y(_186_)
  );
  NOR _579_ (
    .A(_053_),
    .B(_089_),
    .Y(_290_)
  );
  NOR _580_ (
    .A(_290_),
    .B(_310_),
    .Y(_188_)
  );
  NOT _581_ (
    .A(_228_),
    .Y(_291_)
  );
  NOR _582_ (
    .A(_291_),
    .B(_310_),
    .Y(_191_)
  );
  NOT _583_ (
    .A(_229_),
    .Y(_292_)
  );
  NOR _584_ (
    .A(_292_),
    .B(_310_),
    .Y(_194_)
  );
  NOT _585_ (
    .A(_231_),
    .Y(_293_)
  );
  NOR _586_ (
    .A(_293_),
    .B(_310_),
    .Y(_197_)
  );
  NOT _587_ (
    .A(_233_),
    .Y(_294_)
  );
  NOR _588_ (
    .A(_294_),
    .B(_310_),
    .Y(_199_)
  );
  NOT _589_ (
    .A(_235_),
    .Y(_295_)
  );
  NOR _590_ (
    .A(_295_),
    .B(_310_),
    .Y(_202_)
  );
  NOT _591_ (
    .A(_237_),
    .Y(_296_)
  );
  NOR _592_ (
    .A(_296_),
    .B(_310_),
    .Y(_205_)
  );
  NOT _593_ (
    .A(_238_),
    .Y(_297_)
  );
  NOR _594_ (
    .A(_297_),
    .B(_310_),
    .Y(_208_)
  );
  NOT _595_ (
    .A(_240_),
    .Y(_298_)
  );
  NOR _596_ (
    .A(_298_),
    .B(_310_),
    .Y(_211_)
  );
  NOT _597_ (
    .A(_242_),
    .Y(_299_)
  );
  NOR _598_ (
    .A(_299_),
    .B(_310_),
    .Y(_213_)
  );
  NOT _599_ (
    .A(_244_),
    .Y(_300_)
  );
  NOR _600_ (
    .A(_300_),
    .B(_310_),
    .Y(_216_)
  );
  NOR _601_ (
    .A(_051_),
    .B(_310_),
    .Y(_301_)
  );
  NAND _602_ (
    .A(_301_),
    .B(_007_),
    .Y(_302_)
  );
  NOT _603_ (
    .A(_062_),
    .Y(_303_)
  );
  NOR _604_ (
    .A(_034_),
    .B(_303_),
    .Y(_304_)
  );
  NAND _605_ (
    .A(_304_),
    .B(_181_),
    .Y(_305_)
  );
  NAND _606_ (
    .A(_305_),
    .B(_302_),
    .Y(_248_)
  );
  NAND _607_ (
    .A(_006_),
    .B(_181_),
    .Y(_306_)
  );
  NOR _608_ (
    .A(_306_),
    .B(_021_),
    .Y(_283_)
  );
  NOT _609_ (
    .A(_301_),
    .Y(_307_)
  );
  NOR _610_ (
    .A(_307_),
    .B(_007_),
    .Y(_285_)
  );
  DFF _611_ (
    .C(CLK),
    .D(_324_[0]),
    .Q(state[0])
  );
  DFF _612_ (
    .C(CLK),
    .D(_324_[1]),
    .Q(state[1])
  );
  DFF _613_ (
    .C(CLK),
    .D(_316_),
    .Q(state[2])
  );
  DFF _614_ (
    .C(CLK),
    .D(_317_),
    .Q(state[3])
  );
  DFF _615_ (
    .C(CLK),
    .D(_324_[4]),
    .Q(state[4])
  );
  DFF _616_ (
    .C(CLK),
    .D(_000_[0]),
    .Q(oALERT[0])
  );
  DFF _617_ (
    .C(CLK),
    .D(_000_[1]),
    .Q(oALERT[1])
  );
  DFF _618_ (
    .C(CLK),
    .D(_000_[2]),
    .Q(oALERT[2])
  );
  DFF _619_ (
    .C(CLK),
    .D(_000_[3]),
    .Q(oALERT[3])
  );
  DFF _620_ (
    .C(CLK),
    .D(_000_[4]),
    .Q(oALERT[4])
  );
  DFF _621_ (
    .C(CLK),
    .D(_000_[5]),
    .Q(oALERT[5])
  );
  DFF _622_ (
    .C(CLK),
    .D(_000_[6]),
    .Q(oALERT[6])
  );
  DFF _623_ (
    .C(CLK),
    .D(_000_[7]),
    .Q(oALERT[7])
  );
  DFF _624_ (
    .C(CLK),
    .D(_000_[8]),
    .Q(oALERT[8])
  );
  DFF _625_ (
    .C(CLK),
    .D(_000_[9]),
    .Q(oALERT[9])
  );
  DFF _626_ (
    .C(CLK),
    .D(_000_[10]),
    .Q(oALERT[10])
  );
  DFF _627_ (
    .C(CLK),
    .D(_000_[11]),
    .Q(oALERT[11])
  );
  DFF _628_ (
    .C(CLK),
    .D(_000_[12]),
    .Q(oALERT[12])
  );
  DFF _629_ (
    .C(CLK),
    .D(_000_[13]),
    .Q(oALERT[13])
  );
  DFF _630_ (
    .C(CLK),
    .D(_000_[14]),
    .Q(oALERT[14])
  );
  DFF _631_ (
    .C(CLK),
    .D(_000_[15]),
    .Q(oALERT[15])
  );
  DFF _632_ (
    .C(CLK),
    .D(_001_[0]),
    .Q(oDATA_to_Buffer[0])
  );
  DFF _633_ (
    .C(CLK),
    .D(_001_[1]),
    .Q(oDATA_to_Buffer[1])
  );
  DFF _634_ (
    .C(CLK),
    .D(_001_[2]),
    .Q(oDATA_to_Buffer[2])
  );
  DFF _635_ (
    .C(CLK),
    .D(_001_[3]),
    .Q(oDATA_to_Buffer[3])
  );
  DFF _636_ (
    .C(CLK),
    .D(_001_[4]),
    .Q(oDATA_to_Buffer[4])
  );
  DFF _637_ (
    .C(CLK),
    .D(_001_[5]),
    .Q(oDATA_to_Buffer[5])
  );
  DFF _638_ (
    .C(CLK),
    .D(_001_[6]),
    .Q(oDATA_to_Buffer[6])
  );
  DFF _639_ (
    .C(CLK),
    .D(_001_[7]),
    .Q(oDATA_to_Buffer[7])
  );
  DFF _640_ (
    .C(CLK),
    .D(_002_[0]),
    .Q(oDIR_WRITE[0])
  );
  DFF _641_ (
    .C(CLK),
    .D(_002_[1]),
    .Q(oDIR_WRITE[1])
  );
  DFF _642_ (
    .C(CLK),
    .D(_002_[2]),
    .Q(oDIR_WRITE[2])
  );
  DFF _643_ (
    .C(CLK),
    .D(_002_[3]),
    .Q(oDIR_WRITE[3])
  );
  DFF _644_ (
    .C(CLK),
    .D(_002_[4]),
    .Q(oDIR_WRITE[4])
  );
  DFF _645_ (
    .C(CLK),
    .D(_002_[5]),
    .Q(oDIR_WRITE[5])
  );
  DFF _646_ (
    .C(CLK),
    .D(_002_[6]),
    .Q(oDIR_WRITE[6])
  );
  DFF _647_ (
    .C(CLK),
    .D(_002_[7]),
    .Q(oDIR_WRITE[7])
  );
  DFF _648_ (
    .C(CLK),
    .D(_003_),
    .Q(oGoodCRC_to_PHY)
  );
  DFF _649_ (
    .C(CLK),
    .D(_004_[0]),
    .Q(oRECEIVE_BYTE_COUNT[0])
  );
  DFF _650_ (
    .C(CLK),
    .D(_004_[1]),
    .Q(oRECEIVE_BYTE_COUNT[1])
  );
  DFF _651_ (
    .C(CLK),
    .D(_004_[2]),
    .Q(oRECEIVE_BYTE_COUNT[2])
  );
  DFF _652_ (
    .C(CLK),
    .D(_004_[3]),
    .Q(oRECEIVE_BYTE_COUNT[3])
  );
  DFF _653_ (
    .C(CLK),
    .D(_004_[4]),
    .Q(oRECEIVE_BYTE_COUNT[4])
  );
  DFF _654_ (
    .C(CLK),
    .D(_004_[5]),
    .Q(oRECEIVE_BYTE_COUNT[5])
  );
  DFF _655_ (
    .C(CLK),
    .D(_004_[6]),
    .Q(oRECEIVE_BYTE_COUNT[6])
  );
  DFF _656_ (
    .C(CLK),
    .D(_004_[7]),
    .Q(oRECEIVE_BYTE_COUNT[7])
  );
  assign _005_ = iRX_BUF_FRAME_TYPE[0];
  assign _310_ = reset;
  assign _324_[0] = _311_;
  assign _324_[4] = _095_;
  assign _167_ = iALERT[10];
  assign _308_ = state[1];
  assign _309_ = state[3];
  assign _006_ = iRECEIVE_DETECT[0];
  assign _007_ = Unexpected_GoodCRC;
  assign _008_ = Start;
  assign _013_ = iALERT[3];
  assign _015_ = CC_Busy;
  assign _017_ = CC_IDLE;
  assign _020_ = Tx_State_Machine_ACTIVE;
  assign _022_ = oDATA_to_Buffer[0];
  assign _024_ = Data_In[0];
  assign _026_ = oDATA_to_Buffer[1];
  assign _028_ = Data_In[1];
  assign _031_ = oDATA_to_Buffer[2];
  assign _033_ = Data_In[2];
  assign _036_ = oDATA_to_Buffer[3];
  assign _038_ = Data_In[3];
  assign _041_ = oDATA_to_Buffer[4];
  assign _043_ = Data_In[4];
  assign _045_ = oDATA_to_Buffer[5];
  assign _047_ = Data_In[5];
  assign _050_ = oDATA_to_Buffer[6];
  assign _052_ = Data_In[6];
  assign _055_ = oDATA_to_Buffer[7];
  assign _057_ = Data_In[7];
  assign _060_ = oGoodCRC_to_PHY;
  assign _062_ = state[2];
  assign _065_ = oRECEIVE_BYTE_COUNT[0];
  assign _069_ = oRECEIVE_BYTE_COUNT[1];
  assign _072_ = oRECEIVE_BYTE_COUNT[2];
  assign _075_ = oRECEIVE_BYTE_COUNT[3];
  assign _077_ = oRECEIVE_BYTE_COUNT[4];
  assign _080_ = oRECEIVE_BYTE_COUNT[5];
  assign _083_ = oRECEIVE_BYTE_COUNT[6];
  assign _086_ = oRECEIVE_BYTE_COUNT[7];
  assign _089_ = oALERT[5];
  assign _091_ = oDIR_WRITE[0];
  assign _096_ = oDIR_WRITE[1];
  assign _100_ = oDIR_WRITE[2];
  assign _103_ = oDIR_WRITE[3];
  assign _107_ = oDIR_WRITE[4];
  assign _111_ = oDIR_WRITE[5];
  assign _115_ = oDIR_WRITE[6];
  assign _118_ = oDIR_WRITE[7];
  assign _004_[0] = _123_;
  assign _004_[1] = _125_;
  assign _004_[2] = _128_;
  assign _004_[3] = _131_;
  assign _004_[4] = _134_;
  assign _004_[5] = _137_;
  assign _004_[6] = _139_;
  assign _004_[7] = _142_;
  assign _003_ = _144_;
  assign _002_[0] = _146_;
  assign _002_[1] = _148_;
  assign _002_[2] = _150_;
  assign _002_[3] = _151_;
  assign _002_[4] = _153_;
  assign _002_[5] = _154_;
  assign _002_[6] = _156_;
  assign _002_[7] = _158_;
  assign _001_[0] = _160_;
  assign _001_[1] = _161_;
  assign _001_[2] = _163_;
  assign _001_[3] = _165_;
  assign _001_[4] = _168_;
  assign _001_[5] = _169_;
  assign _001_[6] = _171_;
  assign _001_[7] = _173_;
  assign _000_[0] = _175_;
  assign _000_[1] = _178_;
  assign _000_[2] = _180_;
  assign _000_[3] = _183_;
  assign _000_[4] = _186_;
  assign _000_[5] = _188_;
  assign _000_[6] = _191_;
  assign _000_[7] = _194_;
  assign _000_[8] = _197_;
  assign _000_[9] = _199_;
  assign _000_[10] = _202_;
  assign _000_[11] = _205_;
  assign _000_[12] = _208_;
  assign _000_[13] = _211_;
  assign _000_[14] = _213_;
  assign _000_[15] = _216_;
  assign _218_ = oALERT[0];
  assign _220_ = oALERT[1];
  assign _222_ = oALERT[2];
  assign _224_ = oALERT[3];
  assign _226_ = oALERT[4];
  assign _228_ = oALERT[6];
  assign _229_ = oALERT[7];
  assign _231_ = oALERT[8];
  assign _233_ = oALERT[9];
  assign _235_ = oALERT[10];
  assign _237_ = oALERT[11];
  assign _238_ = oALERT[12];
  assign _240_ = oALERT[13];
  assign _242_ = oALERT[14];
  assign _244_ = oALERT[15];
  assign _324_[1] = _248_;
  assign _250_ = iRECEIVE_BYTE_COUNT[4];
  assign _256_ = iRECEIVE_BYTE_COUNT[5];
  assign _258_ = iRECEIVE_BYTE_COUNT[6];
  assign _264_ = iRECEIVE_BYTE_COUNT[3];
  assign _266_ = iRECEIVE_BYTE_COUNT[2];
  assign _268_ = iRECEIVE_BYTE_COUNT[1];
  assign _270_ = iRECEIVE_BYTE_COUNT[0];
  assign _277_ = iRX_BUF_FRAME_TYPE[1];
  assign _279_ = iRX_BUF_FRAME_TYPE[2];
  assign _280_ = state[0];
  assign _282_ = state[4];
  assign _317_ = _283_;
  assign _316_ = _285_;
  assign _288_ = iRECEIVE_BYTE_COUNT[7];
endmodule
