/* Generated by Yosys 0.7 (git sha1 UNKNOWN, gcc 4.9.2-10 -fPIC -Os) */

(* src = "I2C_Module.v:21" *)
module I2C_Module(SCL, CLK, iSDA, Reset, oSDA, RD_DATA, WR_DATA, ADDR, RNW, goodCRC, req);
  (* src = "I2C_Module.v:125" *)
  wire [21:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  (* src = "I2C_Module.v:118" *)
  wire [31:0] _293_;
  wire [15:0] _294_;
  wire [7:0] _295_;
  wire [3:0] _296_;
  wire [1:0] _297_;
  wire [10:0] _298_;
  wire [15:0] _299_;
  wire [10:0] _300_;
  wire [10:0] _301_;
  wire [31:0] _302_;
  wire _303_;
  (* src = "I2C_Module.v:710" *)
  wire _304_;
  (* src = "I2C_Module.v:128|<techmap.v>:428" *)
  wire [21:0] _305_;
  wire _306_;
  wire [31:0] _307_;
  (* src = "<techmap.v>:260|<techmap.v>:203" *)
  wire [31:0] _308_;
  (* src = "I2C_Module.v:128|<techmap.v>:445" *)
  wire _309_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _310_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _311_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _312_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _313_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _314_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _315_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _316_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _317_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _318_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _319_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _320_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _321_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _322_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _323_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _324_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _325_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _326_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _327_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _328_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _329_;
  (* src = "I2C_Module.v:29" *)
  output [7:0] ADDR;
  (* src = "I2C_Module.v:23" *)
  input CLK;
  (* src = "I2C_Module.v:27" *)
  input [15:0] RD_DATA;
  (* src = "I2C_Module.v:30" *)
  output RNW;
  (* src = "I2C_Module.v:65" *)
  wire RW;
  (* src = "I2C_Module.v:25" *)
  input Reset;
  (* src = "I2C_Module.v:22" *)
  input SCL;
  (* src = "I2C_Module.v:28" *)
  output [15:0] WR_DATA;
  (* src = "I2C_Module.v:59" *)
  wire [4:0] count;
  (* src = "I2C_Module.v:66" *)
  wire [21:0] currentState;
  (* src = "I2C_Module.v:31" *)
  output goodCRC;
  (* src = "I2C_Module.v:24" *)
  input iSDA;
  (* src = "I2C_Module.v:66" *)
  wire [21:0] nextState;
  (* src = "I2C_Module.v:26" *)
  output oSDA;
  (* src = "I2C_Module.v:62" *)
  wire [15:0] rSend;
  (* src = "I2C_Module.v:32" *)
  output req;
  (* src = "I2C_Module.v:71" *)
  wire [31:0] timeCounter;
  (* src = "I2C_Module.v:72" *)
  wire timeReset;
  (* src = "I2C_Module.v:69" *)
  wire woSDA;
  NOT _330_ (
    .A(_128_),
    .Y(_228_)
  );
  NOT _331_ (
    .A(_157_),
    .Y(_230_)
  );
  NAND _332_ (
    .A(_153_),
    .B(_121_),
    .Y(_231_)
  );
  NAND _333_ (
    .A(_155_),
    .B(_123_),
    .Y(_233_)
  );
  NOR _334_ (
    .A(_233_),
    .B(_231_),
    .Y(_234_)
  );
  NAND _335_ (
    .A(_234_),
    .B(_125_),
    .Y(_235_)
  );
  NOR _336_ (
    .A(_235_),
    .B(_230_),
    .Y(_236_)
  );
  NAND _337_ (
    .A(_236_),
    .B(_127_),
    .Y(_237_)
  );
  NOR _338_ (
    .A(_237_),
    .B(_228_),
    .Y(_238_)
  );
  NAND _339_ (
    .A(_237_),
    .B(_228_),
    .Y(_239_)
  );
  NOR _340_ (
    .A(_098_),
    .B(_232_),
    .Y(_240_)
  );
  NAND _341_ (
    .A(_240_),
    .B(_239_),
    .Y(_241_)
  );
  NOR _342_ (
    .A(_241_),
    .B(_238_),
    .Y(_227_)
  );
  NOT _343_ (
    .A(_100_),
    .Y(_242_)
  );
  NOT _344_ (
    .A(_127_),
    .Y(_243_)
  );
  NOT _345_ (
    .A(_125_),
    .Y(_244_)
  );
  NOT _346_ (
    .A(_121_),
    .Y(_245_)
  );
  NOT _347_ (
    .A(_153_),
    .Y(_246_)
  );
  NOR _348_ (
    .A(_246_),
    .B(_245_),
    .Y(_247_)
  );
  NOT _349_ (
    .A(_123_),
    .Y(_248_)
  );
  NOT _350_ (
    .A(_155_),
    .Y(_250_)
  );
  NOR _351_ (
    .A(_250_),
    .B(_248_),
    .Y(_251_)
  );
  NAND _352_ (
    .A(_251_),
    .B(_247_),
    .Y(_252_)
  );
  NOR _353_ (
    .A(_252_),
    .B(_244_),
    .Y(_253_)
  );
  NAND _354_ (
    .A(_253_),
    .B(_157_),
    .Y(_254_)
  );
  NOR _355_ (
    .A(_254_),
    .B(_243_),
    .Y(_255_)
  );
  NAND _356_ (
    .A(_255_),
    .B(_128_),
    .Y(_256_)
  );
  NOR _357_ (
    .A(_256_),
    .B(_242_),
    .Y(_257_)
  );
  NAND _358_ (
    .A(_256_),
    .B(_242_),
    .Y(_258_)
  );
  NAND _359_ (
    .A(_258_),
    .B(_240_),
    .Y(_259_)
  );
  NOR _360_ (
    .A(_259_),
    .B(_257_),
    .Y(_249_)
  );
  NOT _361_ (
    .A(_130_),
    .Y(_002_)
  );
  NAND _362_ (
    .A(_238_),
    .B(_100_),
    .Y(_003_)
  );
  NOR _363_ (
    .A(_003_),
    .B(_002_),
    .Y(_004_)
  );
  NAND _364_ (
    .A(_003_),
    .B(_002_),
    .Y(_005_)
  );
  NAND _365_ (
    .A(_005_),
    .B(_240_),
    .Y(_006_)
  );
  NOR _366_ (
    .A(_006_),
    .B(_004_),
    .Y(_001_)
  );
  NOT _367_ (
    .A(_102_),
    .Y(_007_)
  );
  NAND _368_ (
    .A(_257_),
    .B(_130_),
    .Y(_008_)
  );
  NOR _369_ (
    .A(_008_),
    .B(_007_),
    .Y(_009_)
  );
  NAND _370_ (
    .A(_008_),
    .B(_007_),
    .Y(_010_)
  );
  NAND _371_ (
    .A(_010_),
    .B(_240_),
    .Y(_011_)
  );
  NOR _372_ (
    .A(_011_),
    .B(_009_),
    .Y(_018_)
  );
  NOT _373_ (
    .A(_132_),
    .Y(_012_)
  );
  NAND _374_ (
    .A(_004_),
    .B(_102_),
    .Y(_013_)
  );
  NOR _375_ (
    .A(_013_),
    .B(_012_),
    .Y(_014_)
  );
  NAND _376_ (
    .A(_013_),
    .B(_012_),
    .Y(_015_)
  );
  NAND _377_ (
    .A(_015_),
    .B(_240_),
    .Y(_016_)
  );
  NOR _378_ (
    .A(_016_),
    .B(_014_),
    .Y(_028_)
  );
  NOT _379_ (
    .A(_104_),
    .Y(_017_)
  );
  NAND _380_ (
    .A(_009_),
    .B(_132_),
    .Y(_019_)
  );
  NOR _381_ (
    .A(_019_),
    .B(_017_),
    .Y(_020_)
  );
  NAND _382_ (
    .A(_019_),
    .B(_017_),
    .Y(_021_)
  );
  NAND _383_ (
    .A(_021_),
    .B(_240_),
    .Y(_022_)
  );
  NOR _384_ (
    .A(_022_),
    .B(_020_),
    .Y(_053_)
  );
  NOT _385_ (
    .A(_134_),
    .Y(_023_)
  );
  NAND _386_ (
    .A(_014_),
    .B(_104_),
    .Y(_024_)
  );
  NOR _387_ (
    .A(_024_),
    .B(_023_),
    .Y(_025_)
  );
  NAND _388_ (
    .A(_024_),
    .B(_023_),
    .Y(_026_)
  );
  NAND _389_ (
    .A(_026_),
    .B(_240_),
    .Y(_027_)
  );
  NOR _390_ (
    .A(_027_),
    .B(_025_),
    .Y(_063_)
  );
  NOT _391_ (
    .A(_105_),
    .Y(_029_)
  );
  NAND _392_ (
    .A(_020_),
    .B(_134_),
    .Y(_030_)
  );
  NOR _393_ (
    .A(_030_),
    .B(_029_),
    .Y(_031_)
  );
  NAND _394_ (
    .A(_030_),
    .B(_029_),
    .Y(_032_)
  );
  NAND _395_ (
    .A(_032_),
    .B(_240_),
    .Y(_033_)
  );
  NOR _396_ (
    .A(_033_),
    .B(_031_),
    .Y(_080_)
  );
  NOT _397_ (
    .A(_136_),
    .Y(_034_)
  );
  NAND _398_ (
    .A(_025_),
    .B(_105_),
    .Y(_036_)
  );
  NOR _399_ (
    .A(_036_),
    .B(_034_),
    .Y(_038_)
  );
  NAND _400_ (
    .A(_036_),
    .B(_034_),
    .Y(_040_)
  );
  NAND _401_ (
    .A(_040_),
    .B(_240_),
    .Y(_042_)
  );
  NOR _402_ (
    .A(_042_),
    .B(_038_),
    .Y(_090_)
  );
  NOT _403_ (
    .A(_107_),
    .Y(_045_)
  );
  NAND _404_ (
    .A(_031_),
    .B(_136_),
    .Y(_047_)
  );
  NOR _405_ (
    .A(_047_),
    .B(_045_),
    .Y(_048_)
  );
  NAND _406_ (
    .A(_047_),
    .B(_045_),
    .Y(_050_)
  );
  NAND _407_ (
    .A(_050_),
    .B(_240_),
    .Y(_051_)
  );
  NOR _408_ (
    .A(_051_),
    .B(_048_),
    .Y(_118_)
  );
  NOT _409_ (
    .A(_139_),
    .Y(_052_)
  );
  NAND _410_ (
    .A(_038_),
    .B(_107_),
    .Y(_054_)
  );
  NOR _411_ (
    .A(_054_),
    .B(_052_),
    .Y(_055_)
  );
  NAND _412_ (
    .A(_054_),
    .B(_052_),
    .Y(_056_)
  );
  NAND _413_ (
    .A(_056_),
    .B(_240_),
    .Y(_057_)
  );
  NOR _414_ (
    .A(_057_),
    .B(_055_),
    .Y(_138_)
  );
  NOT _415_ (
    .A(_109_),
    .Y(_058_)
  );
  NAND _416_ (
    .A(_048_),
    .B(_139_),
    .Y(_059_)
  );
  NOR _417_ (
    .A(_059_),
    .B(_058_),
    .Y(_060_)
  );
  NAND _418_ (
    .A(_059_),
    .B(_058_),
    .Y(_061_)
  );
  NAND _419_ (
    .A(_061_),
    .B(_240_),
    .Y(_062_)
  );
  NOR _420_ (
    .A(_062_),
    .B(_060_),
    .Y(_167_)
  );
  NOT _421_ (
    .A(_140_),
    .Y(_064_)
  );
  NAND _422_ (
    .A(_055_),
    .B(_109_),
    .Y(_065_)
  );
  NOR _423_ (
    .A(_065_),
    .B(_064_),
    .Y(_066_)
  );
  NAND _424_ (
    .A(_065_),
    .B(_064_),
    .Y(_067_)
  );
  NAND _425_ (
    .A(_067_),
    .B(_240_),
    .Y(_068_)
  );
  NOR _426_ (
    .A(_068_),
    .B(_066_),
    .Y(_174_)
  );
  NOT _427_ (
    .A(_111_),
    .Y(_069_)
  );
  NAND _428_ (
    .A(_060_),
    .B(_140_),
    .Y(_070_)
  );
  NOR _429_ (
    .A(_070_),
    .B(_069_),
    .Y(_071_)
  );
  NAND _430_ (
    .A(_070_),
    .B(_069_),
    .Y(_072_)
  );
  NAND _431_ (
    .A(_072_),
    .B(_240_),
    .Y(_073_)
  );
  NOR _432_ (
    .A(_073_),
    .B(_071_),
    .Y(_191_)
  );
  NOT _433_ (
    .A(_142_),
    .Y(_074_)
  );
  NAND _434_ (
    .A(_066_),
    .B(_111_),
    .Y(_075_)
  );
  NOR _435_ (
    .A(_075_),
    .B(_074_),
    .Y(_076_)
  );
  NAND _436_ (
    .A(_075_),
    .B(_074_),
    .Y(_077_)
  );
  NAND _437_ (
    .A(_077_),
    .B(_240_),
    .Y(_078_)
  );
  NOR _438_ (
    .A(_078_),
    .B(_076_),
    .Y(_202_)
  );
  NOT _439_ (
    .A(_113_),
    .Y(_079_)
  );
  NAND _440_ (
    .A(_071_),
    .B(_142_),
    .Y(_081_)
  );
  NOR _441_ (
    .A(_081_),
    .B(_079_),
    .Y(_082_)
  );
  NAND _442_ (
    .A(_081_),
    .B(_079_),
    .Y(_083_)
  );
  NAND _443_ (
    .A(_083_),
    .B(_240_),
    .Y(_084_)
  );
  NOR _444_ (
    .A(_084_),
    .B(_082_),
    .Y(_216_)
  );
  NOT _445_ (
    .A(_144_),
    .Y(_085_)
  );
  NAND _446_ (
    .A(_076_),
    .B(_113_),
    .Y(_086_)
  );
  NOR _447_ (
    .A(_086_),
    .B(_085_),
    .Y(_087_)
  );
  NAND _448_ (
    .A(_086_),
    .B(_085_),
    .Y(_088_)
  );
  NAND _449_ (
    .A(_088_),
    .B(_240_),
    .Y(_089_)
  );
  NOR _450_ (
    .A(_089_),
    .B(_087_),
    .Y(_217_)
  );
  NOT _451_ (
    .A(_115_),
    .Y(_091_)
  );
  NAND _452_ (
    .A(_082_),
    .B(_144_),
    .Y(_092_)
  );
  NOR _453_ (
    .A(_092_),
    .B(_091_),
    .Y(_093_)
  );
  NAND _454_ (
    .A(_092_),
    .B(_091_),
    .Y(_094_)
  );
  NAND _455_ (
    .A(_094_),
    .B(_240_),
    .Y(_095_)
  );
  NOR _456_ (
    .A(_095_),
    .B(_093_),
    .Y(_218_)
  );
  NOT _457_ (
    .A(_146_),
    .Y(_096_)
  );
  NAND _458_ (
    .A(_087_),
    .B(_115_),
    .Y(_097_)
  );
  NOR _459_ (
    .A(_097_),
    .B(_096_),
    .Y(_099_)
  );
  NAND _460_ (
    .A(_097_),
    .B(_096_),
    .Y(_101_)
  );
  NAND _461_ (
    .A(_101_),
    .B(_240_),
    .Y(_103_)
  );
  NOR _462_ (
    .A(_103_),
    .B(_099_),
    .Y(_219_)
  );
  NOT _463_ (
    .A(_116_),
    .Y(_106_)
  );
  NAND _464_ (
    .A(_093_),
    .B(_146_),
    .Y(_108_)
  );
  NOR _465_ (
    .A(_108_),
    .B(_106_),
    .Y(_110_)
  );
  NAND _466_ (
    .A(_108_),
    .B(_106_),
    .Y(_112_)
  );
  NAND _467_ (
    .A(_112_),
    .B(_240_),
    .Y(_114_)
  );
  NOR _468_ (
    .A(_114_),
    .B(_110_),
    .Y(_220_)
  );
  NOT _469_ (
    .A(_148_),
    .Y(_117_)
  );
  NAND _470_ (
    .A(_099_),
    .B(_116_),
    .Y(_120_)
  );
  NOR _471_ (
    .A(_120_),
    .B(_117_),
    .Y(_122_)
  );
  NAND _472_ (
    .A(_120_),
    .B(_117_),
    .Y(_124_)
  );
  NAND _473_ (
    .A(_124_),
    .B(_240_),
    .Y(_126_)
  );
  NOR _474_ (
    .A(_126_),
    .B(_122_),
    .Y(_221_)
  );
  NOT _475_ (
    .A(_119_),
    .Y(_129_)
  );
  NAND _476_ (
    .A(_110_),
    .B(_148_),
    .Y(_131_)
  );
  NOR _477_ (
    .A(_131_),
    .B(_129_),
    .Y(_133_)
  );
  NAND _478_ (
    .A(_131_),
    .B(_129_),
    .Y(_135_)
  );
  NAND _479_ (
    .A(_135_),
    .B(_240_),
    .Y(_137_)
  );
  NOR _480_ (
    .A(_137_),
    .B(_133_),
    .Y(_222_)
  );
  NOT _481_ (
    .A(_150_),
    .Y(_141_)
  );
  NAND _482_ (
    .A(_122_),
    .B(_119_),
    .Y(_143_)
  );
  NOR _483_ (
    .A(_143_),
    .B(_141_),
    .Y(_145_)
  );
  NAND _484_ (
    .A(_143_),
    .B(_141_),
    .Y(_147_)
  );
  NAND _485_ (
    .A(_147_),
    .B(_240_),
    .Y(_149_)
  );
  NOR _486_ (
    .A(_149_),
    .B(_145_),
    .Y(_223_)
  );
  NAND _487_ (
    .A(_145_),
    .B(_151_),
    .Y(_152_)
  );
  NOT _488_ (
    .A(_152_),
    .Y(_154_)
  );
  NOT _489_ (
    .A(_151_),
    .Y(_156_)
  );
  NAND _490_ (
    .A(_133_),
    .B(_150_),
    .Y(_158_)
  );
  NAND _491_ (
    .A(_158_),
    .B(_156_),
    .Y(_160_)
  );
  NAND _492_ (
    .A(_160_),
    .B(_240_),
    .Y(_161_)
  );
  NOR _493_ (
    .A(_161_),
    .B(_154_),
    .Y(_224_)
  );
  NOT _494_ (
    .A(_159_),
    .Y(_162_)
  );
  NOR _495_ (
    .A(_152_),
    .B(_162_),
    .Y(_163_)
  );
  NAND _496_ (
    .A(_152_),
    .B(_162_),
    .Y(_164_)
  );
  NAND _497_ (
    .A(_164_),
    .B(_240_),
    .Y(_165_)
  );
  NOR _498_ (
    .A(_165_),
    .B(_163_),
    .Y(_225_)
  );
  NOT _499_ (
    .A(_226_),
    .Y(_166_)
  );
  NOT _500_ (
    .A(_240_),
    .Y(_168_)
  );
  NOR _501_ (
    .A(_168_),
    .B(_166_),
    .Y(_229_)
  );
  NOR _502_ (
    .A(_168_),
    .B(_121_),
    .Y(_035_)
  );
  NOR _503_ (
    .A(_153_),
    .B(_121_),
    .Y(_169_)
  );
  NAND _504_ (
    .A(_240_),
    .B(_231_),
    .Y(_170_)
  );
  NOR _505_ (
    .A(_170_),
    .B(_169_),
    .Y(_037_)
  );
  NOR _506_ (
    .A(_231_),
    .B(_248_),
    .Y(_171_)
  );
  NAND _507_ (
    .A(_231_),
    .B(_248_),
    .Y(_172_)
  );
  NAND _508_ (
    .A(_172_),
    .B(_240_),
    .Y(_173_)
  );
  NOR _509_ (
    .A(_173_),
    .B(_171_),
    .Y(_039_)
  );
  NOR _510_ (
    .A(_171_),
    .B(_155_),
    .Y(_175_)
  );
  NAND _511_ (
    .A(_240_),
    .B(_252_),
    .Y(_176_)
  );
  NOR _512_ (
    .A(_176_),
    .B(_175_),
    .Y(_041_)
  );
  NOR _513_ (
    .A(_234_),
    .B(_125_),
    .Y(_177_)
  );
  NAND _514_ (
    .A(_240_),
    .B(_235_),
    .Y(_178_)
  );
  NOR _515_ (
    .A(_178_),
    .B(_177_),
    .Y(_043_)
  );
  NAND _516_ (
    .A(_235_),
    .B(_230_),
    .Y(_179_)
  );
  NAND _517_ (
    .A(_179_),
    .B(_240_),
    .Y(_180_)
  );
  NOR _518_ (
    .A(_180_),
    .B(_236_),
    .Y(_044_)
  );
  NOR _519_ (
    .A(_236_),
    .B(_127_),
    .Y(_181_)
  );
  NAND _520_ (
    .A(_240_),
    .B(_237_),
    .Y(_182_)
  );
  NOR _521_ (
    .A(_182_),
    .B(_181_),
    .Y(_046_)
  );
  NOR _522_ (
    .A(_232_),
    .B(_226_),
    .Y(_183_)
  );
  NAND _523_ (
    .A(_034_),
    .B(_023_),
    .Y(_184_)
  );
  NAND _524_ (
    .A(_064_),
    .B(_052_),
    .Y(_185_)
  );
  NOR _525_ (
    .A(_185_),
    .B(_184_),
    .Y(_186_)
  );
  NAND _526_ (
    .A(_228_),
    .B(_127_),
    .Y(_187_)
  );
  NAND _527_ (
    .A(_012_),
    .B(_002_),
    .Y(_188_)
  );
  NOR _528_ (
    .A(_188_),
    .B(_187_),
    .Y(_189_)
  );
  NAND _529_ (
    .A(_189_),
    .B(_186_),
    .Y(_190_)
  );
  NAND _530_ (
    .A(_156_),
    .B(_141_),
    .Y(_192_)
  );
  NAND _531_ (
    .A(_162_),
    .B(_157_),
    .Y(_193_)
  );
  NOR _532_ (
    .A(_193_),
    .B(_192_),
    .Y(_194_)
  );
  NAND _533_ (
    .A(_117_),
    .B(_096_),
    .Y(_195_)
  );
  NAND _534_ (
    .A(_085_),
    .B(_074_),
    .Y(_196_)
  );
  NOR _535_ (
    .A(_196_),
    .B(_195_),
    .Y(_197_)
  );
  NAND _536_ (
    .A(_197_),
    .B(_194_),
    .Y(_198_)
  );
  NOR _537_ (
    .A(_198_),
    .B(_190_),
    .Y(_199_)
  );
  NAND _538_ (
    .A(_106_),
    .B(_091_),
    .Y(_200_)
  );
  NAND _539_ (
    .A(_125_),
    .B(_129_),
    .Y(_201_)
  );
  NOR _540_ (
    .A(_201_),
    .B(_200_),
    .Y(_203_)
  );
  NAND _541_ (
    .A(_058_),
    .B(_045_),
    .Y(_204_)
  );
  NAND _542_ (
    .A(_079_),
    .B(_069_),
    .Y(_205_)
  );
  NOR _543_ (
    .A(_205_),
    .B(_204_),
    .Y(_206_)
  );
  NAND _544_ (
    .A(_206_),
    .B(_203_),
    .Y(_207_)
  );
  NOT _545_ (
    .A(_169_),
    .Y(_208_)
  );
  NOR _546_ (
    .A(_208_),
    .B(_233_),
    .Y(_209_)
  );
  NAND _547_ (
    .A(_007_),
    .B(_242_),
    .Y(_210_)
  );
  NAND _548_ (
    .A(_029_),
    .B(_017_),
    .Y(_211_)
  );
  NOR _549_ (
    .A(_211_),
    .B(_210_),
    .Y(_212_)
  );
  NAND _550_ (
    .A(_212_),
    .B(_209_),
    .Y(_213_)
  );
  NOR _551_ (
    .A(_213_),
    .B(_207_),
    .Y(_214_)
  );
  NAND _552_ (
    .A(_214_),
    .B(_199_),
    .Y(_215_)
  );
  NAND _553_ (
    .A(_215_),
    .B(_183_),
    .Y(_049_)
  );
  DFF _554_ (
    .C(CLK),
    .D(_000_[0]),
    .Q(RW)
  );
  \$_DLATCH_P_  _555_ (
    .D(1'b1),
    .E(Reset),
    .Q(RW)
  );
  assign ADDR = 8'b00000000;
  assign RNW = 1'b0;
  assign WR_DATA = 16'b0000000000000000;
  assign count = { 1'b0, RW, 3'b000 };
  assign currentState[21:1] = 21'b000000000000000000000;
  assign goodCRC = 1'b0;
  assign nextState = { 21'b000000000000000000000, RW };
  assign oSDA = RW;
  assign rSend = { RW, 1'b0, RW, 1'b0, RW, 1'b0, RW, 1'b0, RW, 1'b0, RW, 1'b0, RW, 1'b0, RW, 1'b0 };
  assign req = 1'b0;
  assign woSDA = RW;
  assign _260_ = timeReset;
  assign _261_ = timeCounter[8];
  assign _262_ = timeCounter[10];
  assign _263_ = timeCounter[12];
  assign _264_ = timeCounter[14];
  assign _265_ = timeCounter[16];
  assign _266_ = timeCounter[18];
  assign _267_ = timeCounter[20];
  assign _268_ = timeCounter[22];
  assign _269_ = timeCounter[24];
  assign _270_ = timeCounter[26];
  assign _271_ = timeCounter[28];
  assign _272_ = timeCounter[0];
  assign _273_ = timeCounter[2];
  assign _274_ = timeCounter[4];
  assign _275_ = timeCounter[6];
  assign _276_ = timeCounter[7];
  assign _277_ = timeCounter[9];
  assign _278_ = timeCounter[11];
  assign _279_ = timeCounter[13];
  assign _280_ = timeCounter[15];
  assign _281_ = timeCounter[17];
  assign _282_ = timeCounter[19];
  assign _283_ = timeCounter[21];
  assign _284_ = timeCounter[23];
  assign _285_ = timeCounter[25];
  assign _286_ = timeCounter[27];
  assign _287_ = timeCounter[29];
  assign _288_ = timeCounter[30];
  assign _289_ = timeCounter[1];
  assign _290_ = timeCounter[3];
  assign _291_ = timeCounter[5];
  assign _292_ = timeCounter[31];
  assign timeCounter[7] = _227_;
  assign timeCounter[8] = _249_;
  assign timeCounter[9] = _001_;
  assign timeCounter[10] = _018_;
  assign timeCounter[11] = _028_;
  assign timeCounter[12] = _053_;
  assign timeCounter[13] = _063_;
  assign timeCounter[14] = _080_;
  assign timeCounter[15] = _090_;
  assign timeCounter[16] = _118_;
  assign timeCounter[17] = _138_;
  assign timeCounter[18] = _167_;
  assign timeCounter[19] = _174_;
  assign timeCounter[20] = _191_;
  assign timeCounter[21] = _202_;
  assign timeCounter[22] = _216_;
  assign timeCounter[23] = _217_;
  assign timeCounter[24] = _218_;
  assign timeCounter[25] = _219_;
  assign timeCounter[26] = _220_;
  assign timeCounter[27] = _221_;
  assign timeCounter[28] = _222_;
  assign timeCounter[29] = _223_;
  assign timeCounter[30] = _224_;
  assign timeCounter[31] = _225_;
  assign _226_ = RW;
  assign timeReset = _229_;
  assign _232_ = Reset;
  assign timeCounter[0] = _035_;
  assign timeCounter[1] = _037_;
  assign timeCounter[2] = _039_;
  assign timeCounter[3] = _041_;
  assign timeCounter[4] = _043_;
  assign timeCounter[5] = _044_;
  assign timeCounter[6] = _046_;
  assign _000_[0] = _049_;
  assign _098_ = _260_;
  assign _100_ = _261_;
  assign _102_ = _262_;
  assign _104_ = _263_;
  assign _105_ = _264_;
  assign _107_ = _265_;
  assign _109_ = _266_;
  assign _111_ = _267_;
  assign _113_ = _268_;
  assign _115_ = _269_;
  assign _116_ = _270_;
  assign _119_ = _271_;
  assign _121_ = _272_;
  assign _123_ = _273_;
  assign _125_ = _274_;
  assign _127_ = _275_;
  assign _128_ = _276_;
  assign _130_ = _277_;
  assign _132_ = _278_;
  assign _134_ = _279_;
  assign _136_ = _280_;
  assign _139_ = _281_;
  assign _140_ = _282_;
  assign _142_ = _283_;
  assign _144_ = _284_;
  assign _146_ = _285_;
  assign _148_ = _286_;
  assign _150_ = _287_;
  assign _151_ = _288_;
  assign _153_ = _289_;
  assign _155_ = _290_;
  assign _157_ = _291_;
  assign _159_ = _292_;
endmodule
